import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { PersonalExercise, CreatePersonalExerciseInput } from '../../types';
import * as dataService from '../../services/dataService';
import { ExerciseFilter, ExerciseForm, AddExerciseButton, ExerciseList, DeleteConfirmDialog } from './components';
import { WORKOUT } from '../../constants';

interface ExerciseLibraryTabProps {
  onSelect?: (exercise: PersonalExercise) => void;
  isSelectionMode?: boolean;
  selectedIds?: Set<string>;
}

interface FormData {
  name: string;
  muscleGroup: string;
  category: string;
  tempo: string;
  tutorialText: string;
  defaultRestTime: number;
  defaultSets: number;
  notes: string;
}

const getInitialFormData = (): FormData => ({
  name: '',
  muscleGroup: '',
  category: 'strength',
  tempo: '',
  tutorialText: '',
  defaultRestTime: WORKOUT.DEFAULT_REST_TIME,
  defaultSets: WORKOUT.DEFAULT_SETS,
  notes: '',
});

// Transform form data to PersonalExercise creation input
// Note: createdAt, id, and useCount are auto-generated by the service
const formDataToExerciseInput = (formData: FormData): CreatePersonalExerciseInput => ({
  name: formData.name,
  targetMuscle: formData.muscleGroup || 'Other',
  secondaryMuscles: [],
  equipment: '',
  instructions: '',
  videoUrl: null,
  imageUrl: null,
  isCustom: true,
  isTimed: false,
  muscleGroup: formData.muscleGroup || 'Other',
  category: formData.category || 'strength',
  tempo: formData.tempo || undefined,
  tutorialText: formData.tutorialText || undefined,
  defaultRestTime: formData.defaultRestTime,
  defaultSets: formData.defaultSets,
  notes: formData.notes || undefined,
  userId: '',
  lastWeight: null,
  lastReps: null,
  personalRecords: [],
});

const ExerciseLibraryTab: React.FC<ExerciseLibraryTabProps> = ({
  onSelect,
  isSelectionMode = false,
  selectedIds,
}) => {
  const [exercises, setExercises] = useState<PersonalExercise[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedMuscleGroup, setSelectedMuscleGroup] = useState<string>('all');
  const [selectedCategory] = useState<string>('all');
  const [showAddForm, setShowAddForm] = useState(false);
  const [exerciseToDelete, setExerciseToDelete] = useState<PersonalExercise | null>(null);
  const [formData, setFormData] = useState<FormData>(getInitialFormData);

  useEffect(() => {
    loadExercises();
  }, []);

  const loadExercises = useCallback(async () => {
    const data = await dataService.getPersonalExercises();
    if (data.length > 0) {
      setExercises(data);
      return;
    }
    // If we got an empty list on first load, the DB open and the built-in seed
    // may have raced. Wait one tick for any in-flight writes to settle, then retry.
    await new Promise<void>(resolve => setTimeout(resolve, 300));
    const retried = await dataService.getPersonalExercises();
    setExercises(retried);
  }, []);

  const handleDelete = useCallback((exercise: PersonalExercise, e: React.MouseEvent) => {
    e.stopPropagation();
    setExerciseToDelete(exercise);
  }, []);

  const confirmDelete = useCallback(async () => {
    if (!exerciseToDelete) return;
    await dataService.deletePersonalExercise(exerciseToDelete.id);
    setExerciseToDelete(null);
    loadExercises();
  }, [exerciseToDelete, loadExercises]);

  const cancelDelete = useCallback(() => {
    setExerciseToDelete(null);
  }, []);

  const handleCreate = useCallback(async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name.trim()) return;

    await dataService.createPersonalExercise(formDataToExerciseInput(formData));

    setFormData(getInitialFormData());
    setShowAddForm(false);
    loadExercises();
  }, [formData, loadExercises]);

  const filteredExercises = useMemo(() => {
    return exercises
      .filter(ex => {
        const matchesSearch = (ex.name ?? '').toLowerCase().includes(searchQuery.toLowerCase());
        const matchesMuscleGroup =
          selectedMuscleGroup === 'all' || ex.muscleGroup === selectedMuscleGroup;
        const matchesCategory = selectedCategory === 'all' || ex.category === selectedCategory;
        return matchesSearch && matchesMuscleGroup && matchesCategory;
      })
      .sort((a, b) => (a.name ?? '').localeCompare(b.name ?? ''));
  }, [exercises, searchQuery, selectedMuscleGroup, selectedCategory]);

  return (
    <div className="flex flex-col h-full bg-transparent overflow-hidden">
      <ExerciseFilter
        searchQuery={searchQuery}
        onSearchChange={setSearchQuery}
        selectedMuscleGroup={selectedMuscleGroup}
        onMuscleGroupChange={setSelectedMuscleGroup}
        exercises={exercises}
        onSuggestionSelect={onSelect}
      />

      <AnimatePresence mode="sync">
        {showAddForm ? (
          <motion.div
            key="form"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden mb-4 shrink-0"
          >
            <ExerciseForm
              formData={formData}
              onChange={setFormData}
              onSubmit={handleCreate}
              onCancel={() => setShowAddForm(false)}
            />
          </motion.div>
        ) : (
          <motion.div
            key="button"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          >
            <AddExerciseButton onClick={() => setShowAddForm(true)} />
          </motion.div>
        )}
      </AnimatePresence>

      <div className="flex-1 overflow-y-auto custom-scrollbar -mr-2 pr-2 pb-10">
        <ExerciseList
          exercises={filteredExercises}
          isSelectionMode={isSelectionMode}
          selectedIds={selectedIds}
          onExerciseClick={onSelect}
          onDeleteExercise={handleDelete}
        />
      </div>

      <DeleteConfirmDialog
        exercise={exerciseToDelete}
        onConfirm={confirmDelete}
        onCancel={cancelDelete}
      />

      <style>{`
        .mask-linear-fade {
          mask-image: linear-gradient(to right, black 85%, transparent 100%);
        }
      `}</style>
    </div>
  );
};

export default React.memo(ExerciseLibraryTab);
