// ============================================================================
// SPARKOS FITNESS APP - TYPES
// ============================================================================
// טיפוסים מ-SparkOS עבור אפליקציית כושר

// ============================================================================
// WORKOUT TYPES
// ============================================================================

/**
 * One weight×reps leg within a single set. Used for drop sets or any set where
 * the load changes mid-set (e.g. 60×8 → 50×6 → 40×4 logged as ONE set). When a
 * set has `segments`, they are the source of truth for its volume; the top-level
 * `weight`/`reps` mirror the first (heaviest) leg for back-compat display.
 */
export interface SetSegment {
  weight: number;
  reps: number;
}

export interface WorkoutSet {
  id: string;
  setNumber: number;
  reps: number;
  weight: number;
  rpe: number | null;
  isWarmup: boolean;
  isCompleted: boolean;
  notes: string;
  /** Subjective set tag from the RPE picker (technique/near-failure/pain/deload). */
  rpeTag?: RpeTag | null;
  completedAt: string | null;
  duration?: number; // for timed exercises (e.g., plank)
  // Intensity techniques (optional — flipped via SET_TECHNIQUE action)
  isDropSet?: boolean;
  isFailure?: boolean;
  isRestPause?: boolean;
  /** Marks sets auto-added by progressive overload / auto-increment */
  autoGenerated?: boolean;
  /**
   * Per-weight legs within this set (drop set / weight changed mid-set). When
   * present and non-empty, volume = Σ(weight×reps) over the segments.
   */
  segments?: SetSegment[];
  /**
   * Set was deliberately skipped (e.g. a warmup the user chose not to do). It is
   * marked completed for flow purposes but contributes no volume/reps and never
   * starts a rest timer.
   */
  skipped?: boolean;
}

export type SetTechnique = 'warmup' | 'dropSet' | 'failure' | 'restPause';

/** Subjective per-set tag chosen in the RPE picker (persisted on the set). */
export type RpeTag = 'clean' | 'near-failure' | 'pain' | 'deload';

export interface WorkoutExercise {
  id: string;
  exerciseId: string;
  exerciseName: string;
  targetMuscle: string;
  sets: WorkoutSet[];
  notes: string;
  restSeconds: number;
  isCompleted: boolean;
  order: number;
  // Extended fields used by components
  name?: string; // Alias for exerciseName (backward compatibility)
  muscleGroup?: string;
  tempo?: string;
  targetRestTime?: number;
  tutorialText?: string;
  programExtras?: ProgramExtras;
}

export interface WorkoutSession {
  id: string;
  date: string; // YYYY-MM-DD
  startTime: string; // ISO timestamp
  endTime: string | null;
  exercises: WorkoutExercise[];
  duration: number; // in seconds
  status: 'active' | 'completed' | 'cancelled';
  templateId: string | null;
  notes: string;
  rating: number | null; // 1-5
  totalVolume: number; // total weight × reps
  caloriesBurned: number | null;
  userId?: string;
  workoutItemId?: string;
  goalType?: string;
  createdAt: string;
  updatedAt: string;
  lastUsed?: string | null;
  timesUsed?: number;
  isFavorite?: boolean;
  muscleGroups?: string[];
  isBuiltin?: boolean;
}

export interface WorkoutTemplate {
  id: string;
  name: string;
  description: string;
  exercises: WorkoutTemplateExercise[];
  createdAt: string;
  updatedAt: string;
  lastUsed: string | null;
  timesUsed: number;
  isFavorite: boolean;
  // Additional fields
  muscleGroups?: string[];
  isBuiltin?: boolean;
  /**
   * Hidden, app-managed template (e.g. the generated current-day of a structured
   * program). Excluded from the user-facing template list and last-used picker,
   * but still loadable by id so the workout runner can start from it.
   */
  isProgramHidden?: boolean;
}

export interface WorkoutTemplateExercise {
  id: string;
  exerciseId: string;
  exerciseName: string;
  targetMuscle: string;
  targetSets: number;
  targetReps: number;
  targetWeight: number | null;
  restSeconds: number;
  order: number;
  notes: string;
  // Extended fields used by components (backward compatibility)
  name?: string; // Alias for exerciseName
  muscleGroup?: string;
  targetRestTime?: number;
  tempo?: string;
  sets?: { reps: number; weight: number }[];
  /** Rich program metadata (RPE target, intensity technique, substitutions, notes). */
  programExtras?: ProgramExtras;
}

// ============================================================================
// EXERCISE TYPES
// ============================================================================

export interface ProgramExtras {
  rpeTarget?: number;
  /** Seconds used by the rest timer — the LOW end of the PDF range (shorter default). */
  restTime?: number;
  intensityTechnique?: string;
  alternatives?: string[];
  notes?: string;
  // Verbatim-from-PDF presentation fields so the UI never re-parses strings:
  /** Rep range, e.g. "8-10" (render LTR/bdi). */
  repRange?: string;
  /** Human rest range in Hebrew, e.g. "3–5 דק'" (already formatted with en-dash). */
  restRange?: string;
  /** Low end of the rest range, in seconds (timer target). */
  restSecondsMin?: number;
  /** High end of the rest range, in seconds. */
  restSecondsMax?: number;
  /** Resolved count of warmup sets prescribed by the program (sets actually created). */
  warmupSets?: number;
  /** Verbatim warmup prescription from the plan, e.g. "2–3" (may be a range). */
  warmupRange?: string;
  /** Number of working sets prescribed by the plan. */
  workingSets?: number;
  /** Early-set RPE cue, e.g. "~6-7". */
  earlyRpe?: string;
  /** Last-set RPE cue, e.g. "~7-8". */
  lastRpe?: string;
  /** The PDF's freeform coaching cue (tempo/pause/setup), kept separate from the
   *  auto-composed `notes` so the UI can format it on its own line. */
  coachingNote?: string;
  [key: string]: unknown;
}

// ----------------------------------------------------------------------------
// AR-1: Decomposed Exercise types (catalog / active-runtime / template)
// ----------------------------------------------------------------------------

/** Identity + catalog metadata for an exercise definition. */
export interface ExerciseCatalogEntry {
  id: string;
  name?: string;
  targetMuscle?: string;
  secondaryMuscles?: string[];
  equipment?: string;
  instructions?: string;
  videoUrl?: string | null;
  imageUrl?: string | null;
  isCustom?: boolean;
  isTimed?: boolean; // e.g., plank - uses duration instead of reps
  createdAt?: string;
}

/** Runtime state of an exercise during an active workout session. */
export interface ActiveExercise extends ExerciseCatalogEntry {
  sets?: WorkoutSet[];
  muscleGroup?: string;
  tempo?: string;
  defaultRestTime?: number;
  targetRestTime?: number;
  tutorialText?: string;
  programExtras?: ProgramExtras;
  isCompleted?: boolean;
  order?: number;
  notes?: string;
  // Legacy compat fields used by save path
  exerciseId?: string;
  exerciseName?: string;
}

/** Exercise shape used in template authoring (target prescriptions). */
export interface TemplateExercise extends ExerciseCatalogEntry {
  targetSets?: number;
  targetReps?: number;
  targetWeight?: number;
  restSeconds?: number;
  order?: number;
  notes?: string;
}

/**
 * Backward-compatible god-object alias.
 * Existing call sites can keep importing `Exercise` without changes.
 * New code should prefer `ActiveExercise` or `TemplateExercise`.
 * @deprecated Prefer ActiveExercise, TemplateExercise, or ExerciseCatalogEntry.
 */
export interface Exercise {
  id: string;
  name?: string;
  targetMuscle?: string;
  secondaryMuscles?: string[];
  equipment?: string;
  instructions?: string;
  videoUrl?: string | null;
  imageUrl?: string | null;
  isCustom?: boolean;
  isTimed?: boolean; // e.g., plank - uses duration instead of reps
  createdAt?: string;
  // Extended fields used by workout components
  sets?: WorkoutSet[];
  muscleGroup?: string;
  tempo?: string;
  defaultRestTime?: number;
  targetRestTime?: number;
  tutorialText?: string;
  programExtras?: ProgramExtras;
  // Additional fields from template/personal exercise context
  targetSets?: number;
  targetReps?: number;
  targetWeight?: number;
  restSeconds?: number;
  order?: number;
  notes?: string;
  exerciseId?: string;
  exerciseName?: string;
  isCompleted?: boolean;
}

// Personal exercise with workout-specific fields
export interface PersonalExercise extends Exercise {
  userId?: string;
  lastWeight?: number | null;
  lastReps?: number | null;
  personalRecords?: ExercisePR[];
  // Workout-specific fields
  muscleGroup?: string;
  tempo?: string;
  defaultRestTime?: number;
  defaultSets?: number; // NEW: number of sets for this exercise
  tutorialText?: string;
  category?: string;
  useCount?: number;
  lastUsed?: string;
  isFavorite?: boolean;
  notes?: string;
}

// Type for creating a new personal exercise (excludes auto-generated fields)
// Made partial to allow creating exercises with minimal data
export type CreatePersonalExerciseInput = Partial<Omit<PersonalExercise, 'id' | 'createdAt'>> & {
  name: string;
  targetMuscle?: string;
};

export interface ExercisePR {
  id: string;
  exerciseId: string;
  date: string;
  type: 'weight' | '1rm' | 'reps' | 'volume';
  value: number;
  reps: number;
  weight: number;
}

// ============================================================================
// WORKOUT CONTEXT
// ============================================================================

// ============================================================================
// NUTRITION TYPES (NEW)
// ============================================================================

export interface MealEntry {
  id: string;
  date: string; // YYYY-MM-DD
  name: string;
  meals: Meal[];
  totalMacros: MacroNutrients;
  notes: string;
  createdAt: string;
}

export interface Meal {
  id: string;
  name: MealType;
  foods: FoodItem[];
  time: string; // HH:MM
  totalMacros: MacroNutrients;
}

export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'pre-workout' | 'post-workout';

export interface FoodItem {
  id: string;
  name: string;
  brand?: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  servingSize: string;
  servings: number;
  barcode?: string;
}

export interface MacroNutrients {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
}

// ============================================================================
// USER GOALS
// ============================================================================

export interface UserGoals {
  id: string;
  fitness: FitnessGoals;
  nutrition: NutritionGoals;
  currentWeight: number;
  targetWeight: number;
  height: number;
  age: number;
  gender: 'male' | 'female' | 'other';
  activityLevel: 'sedentary' | 'light' | 'moderate' | 'active' | 'very_active';
}

export interface FitnessGoals {
  weeklyWorkouts: number;
  workoutDuration: number; // minutes
  targetMuscles: string[];
  preferredWorkoutTime: 'morning' | 'afternoon' | 'evening';
}

export interface NutritionGoals {
  dailyCalories: number;
  dailyProtein: number;
  dailyCarbs: number;
  dailyFat: number;
  mealTiming: MealTiming[];
}

export interface MealTiming {
  meal: MealType;
  targetTime: string; // HH:MM
  caloriesTarget: number;
}

// ============================================================================
// ANALYTICS TYPES
// ============================================================================

export interface WorkoutAnalytics {
  totalWorkouts: number;
  totalVolume: number;
  totalDuration: number;
  averageWorkoutDuration: number;
  mostTrainedMuscles: string[];
  workoutFrequency: { date: string; count: number }[];
  personalRecords: ExercisePR[];
  streakDays: number;
}

export interface NutritionAnalytics {
  averageCalories: number;
  averageProtein: number;
  averageCarbs: number;
  averageFat: number;
  adherenceScore: number; // 0-100
  mealTimingAdherence: number; // 0-100
}

// ============================================================================
// UI TYPES
// ============================================================================

export type WorkoutTheme = 'deepCosmos' | 'fireEnergy' | 'neonPulse' | 'oceanWave' | 'forestGrove';

export interface ThemeColors {
  primary: string;
  secondary: string;
  accent: string;
  background: string;
  surface: string;
  text: string;
  success: string;
  warning: string;
  error: string;
}

// ============================================================================
// ADDITIONAL MISSING TYPES
// ============================================================================

// Personal workout item — composed of Exercise + metadata
export interface PersonalItem {
  // Core ID fields
  id: string;
  createdAt: string;
  updatedAt?: string;

  // Workout metadata
  title?: string;
  workoutDuration?: number;
  isActiveWorkout?: boolean;
  workoutTemplateId?: string;
  type?: string;
  name?: string;

  // Exercise-derived fields (mirrored from Exercise for workout context)
  targetMuscle?: string;
  muscleGroup?: string;
  equipment?: string;
  instructions?: string;
  videoUrl?: string | null;
  imageUrl?: string | null;
  isCustom?: boolean;
  isTimed?: boolean;
  notes?: string;
  category?: string;
  tempo?: string;
  defaultRestTime?: number;
  defaultSets?: number;
  tutorialText?: string;

  // Exercise content
  exercises?: Exercise[];

  // Personal tracking fields
  userId?: string;
  useCount?: number;
  lastUsed?: string;
  isFavorite?: boolean;

  // Workout-specific fields
  workoutStartTime?: string;

  // Optional content
  content?: string;
  isBuiltin?: boolean;
}

// Body weight entry
export interface BodyWeightEntry {
  id: string;
  date: string;
  weight: number;
  notes?: string;
  createdAt: string;
}

// Workout goals (type alias)
export type WorkoutGoal = 'strength' | 'hypertrophy' | 'endurance' | 'maintenance' | 'general';
export type WarmupPreference = 'required' | 'skip' | 'optional' | 'ask' | 'always' | 'never';
/**
 * @deprecated Use {@link WarmupPreference}. Kept as a backward-compat alias so
 * existing importers keep working; the two had identical members.
 */
export type WarmupMode = WarmupPreference;

// Helper to create a properly typed WorkoutSet
export const createWorkoutSet = (
  overrides: Partial<WorkoutSet> & { reps: number; weight: number }
): WorkoutSet => ({
  id:
    crypto.randomUUID?.() ||
    // Fallback: include Date.now() so two sets created in the same tick can't
    // collide on Math.random() alone (cf. utils/id.ts generateId).
    `set-${Date.now()}-${Math.random().toString(36).slice(2)}`,
  setNumber: 0,
  rpe: null,
  isWarmup: false,
  isCompleted: false,
  notes: '',
  completedAt: null,
  ...overrides,
});

// ============================================================================
// APP SETTINGS
// ============================================================================

export interface WorkoutSettings {
  // Display
  oledMode: boolean;
  selectedTheme: WorkoutTheme;

  // Workout defaults
  defaultWorkoutGoal: WorkoutGoal;
  defaultRestTime: number;
  defaultSets: number;
  autoStartRest: boolean;
  warmupPreference: WarmupPreference;
  cooldownPreference: 'always' | 'ask' | 'never';
  enableWarmup?: boolean;
  enableCooldown?: boolean;

  // Behavior
  keepAwake: boolean;
  hapticsEnabled: boolean;
  autoIncrementWeight: boolean;
  weightIncrementAmount: number;

  // Display options
  showGhostValues: boolean;
  showVolumePreview: boolean;
  showIntensityMeter: boolean;
  showPerformanceStats: boolean;
  showSetHistory?: boolean;
  compactMode: boolean;

  // Audio
  soundEnabled: boolean;
  voiceCountdownEnabled: boolean;
  voiceLanguage: 'he-IL' | 'en-US';
  voiceVolume: number;
  countdownBeepEnabled: boolean;
  restTimerVibrate: boolean;
  restTimerSound: boolean;

  // Reminders
  waterReminderEnabled: boolean;
  waterReminderInterval: number;
  workoutRemindersEnabled: boolean;
  workoutReminderTime?: string;
  reminderDays?: number[];
  trackBodyWeight?: boolean;

  // Accessibility
  reducedAnimations: boolean;
  largeText: boolean;
  highContrast: boolean;

  // Progressive Overload
  enableProgressiveOverload: boolean;
  progressiveOverloadPercent: number;
  enableOneRepMaxTracking: boolean;
  showExerciseNotes: boolean;

  // Smart Rest Timer
  smartRestEnabled: boolean;
  shortRestTime: number;
  mediumRestTime: number;
  longRestTime: number;
  extendRestAfterFailure: boolean;

  // Workout Flow
  autoAdvanceExercise: boolean;
  confirmExerciseComplete: boolean;
  enableSupersets: boolean;
  showRestBetweenExercises: boolean;
  /**
   * When true, completing the last set of an exercise automatically appends a
   * fresh set (legacy "infinite sets" behavior). When false (default), the set
   * count is fixed to what the user/template defined and extra sets are added
   * manually via the "add set" button.
   */
  autoAddSets?: boolean;

  // Personal Records
  enablePRAlerts: boolean;
  prCelebrationIntensity: 'off' | 'subtle' | 'full';
  trackVolumeRecords: boolean;

  // Timer Display
  timerDisplayMode: 'countdown' | 'countup' | 'both';
  showTimerInHeader: boolean;

  // Quick Actions
  enableQuickWeightButtons: boolean;
  quickWeightIncrement: number;
  enableQuickRepsButtons: boolean;

  // Gym Mode
  gymModeEnabled: boolean;
  gymModeAutoLock: boolean;

  // Body Weight Prompts
  promptWeightBeforeWorkout: boolean;
  promptWeightAfterWorkout: boolean;

  // Analytics
  enableWorkoutAnalytics: boolean;
  showMuscleGroupBalance: boolean;
  enableExportToCSV: boolean;
}

export interface AppSettings {
  workoutSettings: WorkoutSettings;
  theme: WorkoutTheme;
  soundEnabled: boolean;
  keepAwake: boolean;
  darkMode: boolean;
  unitSystem: 'metric' | 'imperial';
}

export interface PersonalRecord {
  id: string;
  exerciseId: string;
  exerciseName: string;
  date: string;
  weight: number;
  reps: number;
  type: 'weight' | '1rm' | 'reps' | 'volume';
  value?: number; // volume = weight × reps (for volume PRs)
  maxWeight?: number; // optional max weight for volume PRs
  maxWeightReps?: number; // reps at max weight
  maxReps?: number; // for reps PRs
  oneRepMax?: number; // calculated 1RM
}

export type Screen =
  | 'dashboard'
  | 'workout'
  | 'history'
  | 'templates'
  | 'settings'
  | 'today'
  | 'calendar'
  | 'library'
  | 'fitness'
  | 'add'
  | 'login'
  | 'signup'
  | 'insights';

// ============================================================================
// COACH PLATFORM TYPES (re-export)
// ============================================================================
export * from './coach';
