import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { AppSettings, Exercise } from '../../../../types';
import { workoutReducer } from '../workoutReducer';
import type { WorkoutState } from '../workoutTypes';
import { createInitialState } from '../workoutTypes';

// Helper: minimal AppSettings
const mkSettings = (overrides: Partial<AppSettings['workoutSettings']> = {}): AppSettings =>
  ({
    workoutSettings: {
      defaultRestTime: 60,
      autoStartRest: true,
      autoIncrementWeight: false,
      weightIncrementAmount: 2.5,
      enableProgressiveOverload: false,
      hapticsEnabled: false,
      smartRestEnabled: false,
      autoAdvanceExercise: false,
      prCelebrationIntensity: 'off',
      ...overrides,
    },
    theme: 'dark',
    soundEnabled: false,
    keepAwake: false,
    darkMode: true,
    unitSystem: 'metric',
  }) as unknown as AppSettings;

// Helper: minimal exercise with one set
const mkExercise = (overrides: Partial<Exercise> = {}): Exercise => ({
  id: 'ex-1',
  name: 'Bench Press',
  sets: [
    {
      id: 'set-1',
      setNumber: 1,
      reps: 10,
      weight: 80,
      rpe: null,
      isWarmup: false,
      isCompleted: false,
      notes: '',
      completedAt: null,
    },
  ],
  ...overrides,
});

// Helper: apply action to state (reducer mutates draft in place)
const apply = (state: WorkoutState, action: Parameters<typeof workoutReducer>[1]): WorkoutState => {
  const draft = structuredClone(state);
  workoutReducer(draft, action);
  return draft;
};

describe('workoutReducer', () => {
  let baseState: WorkoutState;

  beforeEach(() => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2026-05-15T12:00:00Z'));
    baseState = createInitialState([mkExercise()], 0, mkSettings());
  });

  // ============================================================
  // COMPLETE_SET
  // ============================================================
  describe('COMPLETE_SET', () => {
    it('marks the active set as completed with completedAt and isCompleted in sync', () => {
      const next = apply(baseState, { type: 'COMPLETE_SET' });
      const set = next.exercises[0]!.sets![0]!;
      expect(set.isCompleted).toBe(true);
      expect(set.completedAt).toBe(new Date().toISOString());
    });

    it('adds an auto-generated next set after completing the last set', () => {
      const next = apply(baseState, { type: 'COMPLETE_SET' });
      const sets = next.exercises[0]!.sets!;
      expect(sets).toHaveLength(2);
      expect(sets[1]!.autoGenerated).toBe(true);
      expect(sets[1]!.isCompleted).toBe(false);
      expect(sets[1]!.completedAt).toBeNull();
      expect(sets[1]!.setNumber).toBe(2);
    });

    it('inherits weight and reps from the completed set to the next set', () => {
      const next = apply(baseState, { type: 'COMPLETE_SET' });
      const nextSet = next.exercises[0]!.sets![1]!;
      expect(nextSet.weight).toBe(80);
      expect(nextSet.reps).toBe(10);
    });

    it('applies auto-increment weight when enabled', () => {
      const state = createInitialState(
        [mkExercise()],
        0,
        mkSettings({ autoIncrementWeight: true, weightIncrementAmount: 5 })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      const nextSet = next.exercises[0]!.sets![1]!;
      expect(nextSet.weight).toBe(85); // 80 + 5
    });

    it('applies auto-increment via enableProgressiveOverload', () => {
      const state = createInitialState(
        [mkExercise()],
        0,
        mkSettings({ enableProgressiveOverload: true, weightIncrementAmount: 2.5 })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.exercises[0]!.sets![1]!.weight).toBe(82.5);
    });

    it('starts rest timer with default rest time', () => {
      const next = apply(baseState, { type: 'COMPLETE_SET' });
      expect(next.restTimer.active).toBe(true);
      expect(next.restTimer.totalTime).toBe(60);
      expect(next.restTimer.endTime).toBe(Date.now() + 60000);
    });

    it('does not start rest timer when autoStartRest is false', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ autoStartRest: false }));
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.restTimer.active).toBe(false);
    });

    it('uses targetRestTime from exercise when set', () => {
      const state = createInitialState([mkExercise({ targetRestTime: 120 })], 0, mkSettings());
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.restTimer.totalTime).toBe(120);
    });

    it('uses programExtras.restTime when present', () => {
      const state = createInitialState(
        [mkExercise({ programExtras: { restTime: 120 } })],
        0,
        mkSettings()
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.restTimer.totalTime).toBe(120);
    });

    it('drop-set rest time is 0 (no rest timer)', () => {
      const ex = mkExercise();
      ex.sets![0]!.isDropSet = true;
      const state = createInitialState([ex], 0, mkSettings());
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.restTimer.active).toBe(false);
    });

    it('sets pendingHaptic when hapticsEnabled', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ hapticsEnabled: true }));
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.pendingHaptic).toBe('SET_COMPLETE');
    });

    it('sets showConfetti when prCelebrationIntensity is full', () => {
      const state = createInitialState(
        [mkExercise()],
        0,
        mkSettings({ prCelebrationIntensity: 'full' })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.showConfetti).toBe(true);
    });

    it('does not add next set if completing a non-last set', () => {
      const ex = mkExercise();
      ex.sets = [
        {
          id: 's1',
          setNumber: 1,
          reps: 10,
          weight: 80,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
        },
        {
          id: 's2',
          setNumber: 2,
          reps: 10,
          weight: 80,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
        },
      ];
      const state = createInitialState([ex], 0, mkSettings());
      const next = apply(state, { type: 'COMPLETE_SET' });
      // Completes set 1 (active=0), set 2 already exists, no new set added
      expect(next.exercises[0]!.sets!).toHaveLength(2);
    });

    it('handles exercise with no sets gracefully (creates empty set)', () => {
      const ex = mkExercise();
      ex.sets = [];
      const state = createInitialState([ex], 0, mkSettings());
      const next = apply(state, { type: 'COMPLETE_SET' });
      // Creates an empty set at index 0, completes it, adds next
      expect(next.exercises[0]!.sets!.length).toBeGreaterThanOrEqual(1);
      expect(next.exercises[0]!.sets![0]!.isCompleted).toBe(true);
    });

    it('smart rest uses long rest for Legs', () => {
      const state = createInitialState(
        [mkExercise({ muscleGroup: 'Legs' })],
        0,
        mkSettings({ smartRestEnabled: true, longRestTime: 180 })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.restTimer.totalTime).toBe(180);
    });

    it('smart rest scales by strength goal', () => {
      const state = createInitialState(
        [mkExercise({ muscleGroup: 'Legs' })],
        0,
        mkSettings({ smartRestEnabled: true, longRestTime: 180, defaultWorkoutGoal: 'strength' })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      // 180 * 1.8 = 324
      expect(next.restTimer.totalTime).toBe(324);
    });

    it('smart rest clamps to 600 max', () => {
      const state = createInitialState(
        [mkExercise({ muscleGroup: 'Legs' })],
        0,
        mkSettings({ smartRestEnabled: true, longRestTime: 400, defaultWorkoutGoal: 'strength' })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      // 400 * 1.8 = 720 → clamped to 600
      expect(next.restTimer.totalTime).toBe(600);
    });

    it('smart rest clamps to 30 min for endurance', () => {
      const state = createInitialState(
        [mkExercise({ muscleGroup: 'Arms' })],
        0,
        mkSettings({ smartRestEnabled: true, shortRestTime: 50, defaultWorkoutGoal: 'endurance' })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      // 50 * 0.5 = 25 → clamped to 30
      expect(next.restTimer.totalTime).toBe(30);
    });
  });

  // ============================================================
  // SUPERSET AUTO-ADVANCE
  // ============================================================
  describe('COMPLETE_SET — superset auto-advance', () => {
    it('advances to next exercise in superset group (not last)', () => {
      const exercises: Exercise[] = [
        mkExercise({ id: 'ex-1', name: 'Bench' }),
        mkExercise({ id: 'ex-2', name: 'Row' }),
      ];
      const state = createInitialState(exercises, 0, mkSettings());
      state.supersetGroups = [{ id: 'ss-1', exercises: ['ex-1', 'ex-2'], restBetweenRounds: 90 }];
      state.currentExerciseIndex = 0;

      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.currentExerciseIndex).toBe(1);
      // Short transitional rest (15s)
      expect(next.restTimer.totalTime).toBe(15);
    });

    it('uses restBetweenRounds when completing last exercise in superset', () => {
      const exercises: Exercise[] = [
        mkExercise({ id: 'ex-1', name: 'Bench' }),
        mkExercise({ id: 'ex-2', name: 'Row' }),
      ];
      const state = createInitialState(exercises, 0, mkSettings());
      state.supersetGroups = [{ id: 'ss-1', exercises: ['ex-1', 'ex-2'], restBetweenRounds: 90 }];
      state.currentExerciseIndex = 1; // last in group

      const next = apply(state, { type: 'COMPLETE_SET' });
      // Does NOT advance (stays at 1)
      expect(next.currentExerciseIndex).toBe(1);
      expect(next.restTimer.totalTime).toBe(90);
    });
  });

  // ============================================================
  // UNDO_LAST_SET
  // ============================================================
  describe('UNDO_LAST_SET', () => {
    it('clears completedAt and isCompleted on the last completed set', () => {
      let state = apply(baseState, { type: 'COMPLETE_SET' });
      state = apply(state, { type: 'UNDO_LAST_SET' });
      const set = state.exercises[0]!.sets![0]!;
      expect(set.isCompleted).toBe(false);
      expect(set.completedAt).toBeNull();
    });

    it('removes auto-generated orphan set after undo', () => {
      let state = apply(baseState, { type: 'COMPLETE_SET' });
      expect(state.exercises[0]!.sets!).toHaveLength(2);
      state = apply(state, { type: 'UNDO_LAST_SET' });
      expect(state.exercises[0]!.sets!).toHaveLength(1);
    });

    it('stops rest timer on undo', () => {
      let state = apply(baseState, { type: 'COMPLETE_SET' });
      expect(state.restTimer.active).toBe(true);
      state = apply(state, { type: 'UNDO_LAST_SET' });
      expect(state.restTimer.active).toBe(false);
    });

    it('clears pendingHaptic and showConfetti on undo', () => {
      const s = createInitialState(
        [mkExercise()],
        0,
        mkSettings({ hapticsEnabled: true, prCelebrationIntensity: 'full' })
      );
      let state = apply(s, { type: 'COMPLETE_SET' });
      state = apply(state, { type: 'UNDO_LAST_SET' });
      expect(state.pendingHaptic).toBeNull();
      expect(state.showConfetti).toBe(false);
    });

    it('is a no-op when no sets are completed', () => {
      const next = apply(baseState, { type: 'UNDO_LAST_SET' });
      expect(next.exercises[0]!.sets!).toHaveLength(1);
      expect(next.exercises[0]!.sets![0]!.isCompleted).toBe(false);
    });

    it('does not remove a non-auto-generated next set with data', () => {
      const ex = mkExercise();
      ex.sets = [
        {
          id: 's1',
          setNumber: 1,
          reps: 10,
          weight: 80,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
        },
        {
          id: 's2',
          setNumber: 2,
          reps: 8,
          weight: 85,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
        },
      ];
      const state = createInitialState([ex], 0, mkSettings());
      // Complete first set
      let next = apply(state, { type: 'COMPLETE_SET' });
      // Undo — should NOT remove s2 because it has data (reps=8, weight=85)
      next = apply(next, { type: 'UNDO_LAST_SET' });
      expect(next.exercises[0]!.sets!).toHaveLength(2);
    });
  });

  // ============================================================
  // TOGGLE_PAUSE
  // ============================================================
  describe('TOGGLE_PAUSE', () => {
    it('toggles isPaused from false to true', () => {
      const next = apply(baseState, { type: 'TOGGLE_PAUSE' });
      expect(next.isPaused).toBe(true);
      expect(next.lastPauseTimestamp).toBe(Date.now());
    });

    it('toggles isPaused from true to false and accumulates paused time', () => {
      let state = apply(baseState, { type: 'TOGGLE_PAUSE' });
      vi.advanceTimersByTime(5000);
      state = apply(state, { type: 'TOGGLE_PAUSE' });
      expect(state.isPaused).toBe(false);
      expect(state.totalPausedTime).toBe(5000);
      expect(state.lastPauseTimestamp).toBeNull();
    });

    it('freezes rest timer endTime as negative remaining ms on pause', () => {
      // Start rest timer
      let state = apply(baseState, { type: 'COMPLETE_SET' });
      expect(state.restTimer.active).toBe(true);
      const endTime = state.restTimer.endTime!;

      vi.advanceTimersByTime(10000); // 10s pass
      state = apply(state, { type: 'TOGGLE_PAUSE' });

      // endTime should be negative (frozen remaining ms)
      const expectedRemaining = endTime - Date.now(); // should be 50000
      expect(state.restTimer.endTime).toBe(-expectedRemaining);
      expect(state.restTimer.endTime!).toBeLessThanOrEqual(0);
    });

    it('thaws rest timer with fresh absolute endTime on resume', () => {
      let state = apply(baseState, { type: 'COMPLETE_SET' });
      vi.advanceTimersByTime(10000);
      state = apply(state, { type: 'TOGGLE_PAUSE' }); // freeze
      const frozenRemaining = -state.restTimer.endTime!;

      vi.advanceTimersByTime(30000); // 30s paused
      state = apply(state, { type: 'TOGGLE_PAUSE' }); // thaw

      expect(state.restTimer.endTime).toBe(Date.now() + frozenRemaining);
      expect(state.restTimer.endTime!).toBeGreaterThan(0);
    });
  });

  // ============================================================
  // NUMPAD_SUBMIT
  // ============================================================
  describe('NUMPAD_SUBMIT', () => {
    it('sets weight on the active set from numpad value', () => {
      const state = structuredClone(baseState);
      state.numpad = { isOpen: true, target: 'weight', value: '100' };
      const next = apply(state, { type: 'NUMPAD_SUBMIT' });
      expect(next.exercises[0]!.sets![0]!.weight).toBe(100);
      expect(next.numpad.isOpen).toBe(false);
    });

    it('sets reps as rounded integer', () => {
      const state = structuredClone(baseState);
      state.numpad = { isOpen: true, target: 'reps', value: '8.7' };
      const next = apply(state, { type: 'NUMPAD_SUBMIT' });
      expect(next.exercises[0]!.sets![0]!.reps).toBe(9);
    });

    it('clamps reps to 0 minimum', () => {
      const state = structuredClone(baseState);
      state.numpad = { isOpen: true, target: 'reps', value: '-5' };
      const next = apply(state, { type: 'NUMPAD_SUBMIT' });
      expect(next.exercises[0]!.sets![0]!.reps).toBe(0);
    });

    it('ignores NaN numpad value', () => {
      const state = structuredClone(baseState);
      state.numpad = { isOpen: true, target: 'weight', value: 'abc' };
      const next = apply(state, { type: 'NUMPAD_SUBMIT' });
      expect(next.exercises[0]!.sets![0]!.weight).toBe(80);
    });

    it('is a no-op when target is null', () => {
      const state = structuredClone(baseState);
      state.numpad = { isOpen: true, target: null, value: '100' };
      const next = apply(state, { type: 'NUMPAD_SUBMIT' });
      expect(next.exercises[0]!.sets![0]!.weight).toBe(80);
    });
  });

  // ============================================================
  // EDGE CASES
  // ============================================================
  describe('edge cases', () => {
    it('COMPLETE_SET with empty exercises array is a no-op', () => {
      const state = createInitialState([], 0, mkSettings());
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.exercises).toHaveLength(0);
    });

    it('UNDO_LAST_SET with empty exercises array is a no-op', () => {
      const state = createInitialState([], 0, mkSettings());
      const next = apply(state, { type: 'UNDO_LAST_SET' });
      expect(next.exercises).toHaveLength(0);
    });

    it('completedAt and isCompleted stay in sync across multiple complete/undo cycles', () => {
      let state = baseState;
      // Complete
      state = apply(state, { type: 'COMPLETE_SET' });
      expect(state.exercises[0]!.sets![0]!.isCompleted).toBe(true);
      expect(state.exercises[0]!.sets![0]!.completedAt).not.toBeNull();
      // Undo
      state = apply(state, { type: 'UNDO_LAST_SET' });
      expect(state.exercises[0]!.sets![0]!.isCompleted).toBe(false);
      expect(state.exercises[0]!.sets![0]!.completedAt).toBeNull();
      // Complete again
      state = apply(state, { type: 'COMPLETE_SET' });
      expect(state.exercises[0]!.sets![0]!.isCompleted).toBe(true);
      expect(state.exercises[0]!.sets![0]!.completedAt).not.toBeNull();
    });

    it('timed exercise creates next set with duration inherited', () => {
      const ex = mkExercise({ isTimed: true });
      ex.sets = [
        {
          id: 's1',
          setNumber: 1,
          reps: 0,
          weight: 0,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
          duration: 30,
        },
      ];
      const state = createInitialState([ex], 0, mkSettings());
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.exercises[0]!.sets![1]!.duration).toBe(30);
      expect(next.exercises[0]!.sets![1]!.reps).toBe(0);
    });
  });
});
