import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { AppSettings, Exercise } from '../../../../types';
import { workoutReducer } from '../workoutReducer';
import type { WorkoutState } from '../workoutTypes';
import { createInitialState } from '../workoutTypes';

// Helper: minimal AppSettings
const mkSettings = (overrides: Partial<AppSettings['workoutSettings']> = {}): AppSettings =>
  ({
    workoutSettings: {
      defaultRestTime: 60,
      autoStartRest: true,
      autoIncrementWeight: false,
      weightIncrementAmount: 2.5,
      enableProgressiveOverload: false,
      hapticsEnabled: false,
      smartRestEnabled: false,
      autoAdvanceExercise: false,
      prCelebrationIntensity: 'off',
      // Legacy auto-append flow on by default in this fixture so the existing
      // COMPLETE_SET append tests stay valid. The new default-off behavior is
      // covered explicitly in the "autoAddSets" + "ADD_SET" describe blocks.
      autoAddSets: true,
      ...overrides,
    },
    theme: 'dark',
    soundEnabled: false,
    keepAwake: false,
    darkMode: true,
    unitSystem: 'metric',
  }) as unknown as AppSettings;

// Helper: minimal exercise with one set
const mkExercise = (overrides: Partial<Exercise> = {}): Exercise => ({
  id: 'ex-1',
  name: 'Bench Press',
  sets: [
    {
      id: 'set-1',
      setNumber: 1,
      reps: 10,
      weight: 80,
      rpe: null,
      isWarmup: false,
      isCompleted: false,
      notes: '',
      completedAt: null,
    },
  ],
  ...overrides,
});

// Helper: apply action to state (reducer mutates draft in place)
const apply = (state: WorkoutState, action: Parameters<typeof workoutReducer>[1]): WorkoutState => {
  const draft = structuredClone(state);
  workoutReducer(draft, action);
  return draft;
};

describe('workoutReducer', () => {
  let baseState: WorkoutState;

  beforeEach(() => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2026-05-15T12:00:00Z'));
    baseState = createInitialState([mkExercise()], 0, mkSettings());
  });

  // ============================================================
  // COMPLETE_SET
  // ============================================================
  describe('COMPLETE_SET', () => {
    it('marks the active set as completed with completedAt and isCompleted in sync', () => {
      const next = apply(baseState, { type: 'COMPLETE_SET' });
      const set = next.exercises[0]!.sets![0]!;
      expect(set.isCompleted).toBe(true);
      expect(set.completedAt).toBe(new Date().toISOString());
    });

    it('adds an auto-generated next set after completing the last set', () => {
      const next = apply(baseState, { type: 'COMPLETE_SET' });
      const sets = next.exercises[0]!.sets!;
      expect(sets).toHaveLength(2);
      expect(sets[1]!.autoGenerated).toBe(true);
      expect(sets[1]!.isCompleted).toBe(false);
      expect(sets[1]!.completedAt).toBeNull();
      expect(sets[1]!.setNumber).toBe(2);
    });

    it('inherits weight and reps from the completed set to the next set', () => {
      const next = apply(baseState, { type: 'COMPLETE_SET' });
      const nextSet = next.exercises[0]!.sets![1]!;
      expect(nextSet.weight).toBe(80);
      expect(nextSet.reps).toBe(10);
    });

    it('applies auto-increment weight when enabled', () => {
      const state = createInitialState(
        [mkExercise()],
        0,
        mkSettings({ autoIncrementWeight: true, weightIncrementAmount: 5 })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      const nextSet = next.exercises[0]!.sets![1]!;
      expect(nextSet.weight).toBe(85); // 80 + 5
    });

    it('applies auto-increment via enableProgressiveOverload', () => {
      const state = createInitialState(
        [mkExercise()],
        0,
        mkSettings({ enableProgressiveOverload: true, weightIncrementAmount: 2.5 })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.exercises[0]!.sets![1]!.weight).toBe(82.5);
    });

    it('starts rest timer with default rest time', () => {
      const next = apply(baseState, { type: 'COMPLETE_SET' });
      expect(next.restTimer.active).toBe(true);
      expect(next.restTimer.totalTime).toBe(60);
      expect(next.restTimer.endTime).toBe(Date.now() + 60000);
    });

    it('does not start rest timer when autoStartRest is false', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ autoStartRest: false }));
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.restTimer.active).toBe(false);
    });

    it('uses targetRestTime from exercise when set', () => {
      const state = createInitialState([mkExercise({ targetRestTime: 120 })], 0, mkSettings());
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.restTimer.totalTime).toBe(120);
    });

    it('uses programExtras.restTime when present', () => {
      const state = createInitialState(
        [mkExercise({ programExtras: { restTime: 120 } })],
        0,
        mkSettings()
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.restTimer.totalTime).toBe(120);
    });

    it('drop-set rest time is 0 (no rest timer)', () => {
      const ex = mkExercise();
      ex.sets![0]!.isDropSet = true;
      const state = createInitialState([ex], 0, mkSettings());
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.restTimer.active).toBe(false);
    });

    it('sets pendingHaptic when hapticsEnabled', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ hapticsEnabled: true }));
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.pendingHaptic).toBe('SET_COMPLETE');
    });

    it('does NOT set showConfetti on set completion even when intensity is full', () => {
      // Confetti is gated on an actual PR (SHOW_PR_CELEBRATION), not mere set
      // completion. See the SHOW_PR_CELEBRATION suite for the PR-gated behavior.
      const state = createInitialState(
        [mkExercise()],
        0,
        mkSettings({ prCelebrationIntensity: 'full' })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.showConfetti).toBe(false);
    });

    it('does not add next set if completing a non-last set', () => {
      const ex = mkExercise();
      ex.sets = [
        {
          id: 's1',
          setNumber: 1,
          reps: 10,
          weight: 80,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
        },
        {
          id: 's2',
          setNumber: 2,
          reps: 10,
          weight: 80,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
        },
      ];
      const state = createInitialState([ex], 0, mkSettings());
      const next = apply(state, { type: 'COMPLETE_SET' });
      // Completes set 1 (active=0), set 2 already exists, no new set added
      expect(next.exercises[0]!.sets!).toHaveLength(2);
    });

    it('handles exercise with no sets gracefully (creates empty set)', () => {
      const ex = mkExercise();
      ex.sets = [];
      const state = createInitialState([ex], 0, mkSettings());
      const next = apply(state, { type: 'COMPLETE_SET' });
      // Creates an empty set at index 0, completes it, adds next
      expect(next.exercises[0]!.sets!.length).toBeGreaterThanOrEqual(1);
      expect(next.exercises[0]!.sets![0]!.isCompleted).toBe(true);
    });

    it('smart rest uses long rest for Legs', () => {
      const state = createInitialState(
        [mkExercise({ muscleGroup: 'Legs' })],
        0,
        mkSettings({ smartRestEnabled: true, longRestTime: 180 })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.restTimer.totalTime).toBe(180);
    });

    it('smart rest scales by strength goal', () => {
      const state = createInitialState(
        [mkExercise({ muscleGroup: 'Legs' })],
        0,
        mkSettings({ smartRestEnabled: true, longRestTime: 180, defaultWorkoutGoal: 'strength' })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      // 180 * 1.8 = 324
      expect(next.restTimer.totalTime).toBe(324);
    });

    it('smart rest clamps to 600 max', () => {
      const state = createInitialState(
        [mkExercise({ muscleGroup: 'Legs' })],
        0,
        mkSettings({ smartRestEnabled: true, longRestTime: 400, defaultWorkoutGoal: 'strength' })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      // 400 * 1.8 = 720 → clamped to 600
      expect(next.restTimer.totalTime).toBe(600);
    });

    it('smart rest clamps to 30 min for endurance', () => {
      const state = createInitialState(
        [mkExercise({ muscleGroup: 'Arms' })],
        0,
        mkSettings({ smartRestEnabled: true, shortRestTime: 50, defaultWorkoutGoal: 'endurance' })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      // 50 * 0.5 = 25 → clamped to 30
      expect(next.restTimer.totalTime).toBe(30);
    });
  });

  // ============================================================
  // autoAddSets — default-off behavior
  // ============================================================
  describe('COMPLETE_SET — autoAddSets disabled (default)', () => {
    it('does NOT append a new set when autoAddSets is false', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ autoAddSets: false }));
      const next = apply(state, { type: 'COMPLETE_SET' });
      // The single set is completed but no auto-generated set is appended.
      expect(next.exercises[0]!.sets!).toHaveLength(1);
      expect(next.exercises[0]!.sets![0]!.isCompleted).toBe(true);
    });

    it('still starts the rest timer when autoAddSets is false', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ autoAddSets: false }));
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.restTimer.active).toBe(true);
      expect(next.restTimer.totalTime).toBe(60);
    });
  });

  // ============================================================
  // COMPLETE_SET / NUMPAD_SUBMIT — junk-set guard after full completion
  // ============================================================
  describe('COMPLETE_SET — no junk sets after full completion', () => {
    it('is a no-op when completing an already fully-completed exercise', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ autoAddSets: false }));
      // Complete the only set → exercise is now fully done.
      let next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.exercises[0]!.sets!).toHaveLength(1);
      expect(next.exercises[0]!.sets![0]!.isCompleted).toBe(true);
      // A second COMPLETE_SET (e.g. an accidental slide) must NOT fabricate a
      // junk 0×0 set on the virtual slot past the end.
      next = apply(next, { type: 'COMPLETE_SET' });
      expect(next.exercises[0]!.sets!).toHaveLength(1);
    });

    it('ADD_SET then COMPLETE_SET flows correctly after completion', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ autoAddSets: false }));
      let next = apply(state, { type: 'COMPLETE_SET' }); // 1/1 done
      next = apply(next, { type: 'ADD_SET' }); // manual extra set → 1 done, 1 open
      expect(next.exercises[0]!.sets!).toHaveLength(2);
      expect(next.exercises[0]!.sets![1]!.isCompleted).toBe(false);
      next = apply(next, { type: 'COMPLETE_SET' }); // completes the new set
      expect(next.exercises[0]!.sets!).toHaveLength(2);
      expect(next.exercises[0]!.sets![1]!.isCompleted).toBe(true);
    });

    it('NUMPAD_SUBMIT does not create a junk set when the exercise is fully completed', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ autoAddSets: false }));
      const completed = apply(state, { type: 'COMPLETE_SET' });
      const numpadState = structuredClone(completed);
      numpadState.numpad = { isOpen: true, target: 'weight', value: '100' };
      const next = apply(numpadState, { type: 'NUMPAD_SUBMIT' });
      expect(next.exercises[0]!.sets!).toHaveLength(1);
      expect(next.numpad.isOpen).toBe(false);
      // The already-completed set's weight is untouched (80 from the fixture).
      expect(next.exercises[0]!.sets![0]!.weight).toBe(80);
    });
  });

  // ============================================================
  // ADD_SET — manual set append
  // ============================================================
  describe('ADD_SET', () => {
    it('appends a new uncompleted set inheriting weight and reps from the last set', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ autoAddSets: false }));
      const next = apply(state, { type: 'ADD_SET' });
      const sets = next.exercises[0]!.sets!;
      expect(sets).toHaveLength(2);
      expect(sets[1]!.weight).toBe(80);
      expect(sets[1]!.reps).toBe(10);
      expect(sets[1]!.isCompleted).toBe(false);
      expect(sets[1]!.completedAt).toBeNull();
      expect(sets[1]!.setNumber).toBe(2);
    });

    it('creates a first set when the exercise has none', () => {
      const ex = mkExercise();
      ex.sets = [];
      const state = createInitialState([ex], 0, mkSettings());
      const next = apply(state, { type: 'ADD_SET' });
      expect(next.exercises[0]!.sets!).toHaveLength(1);
      expect(next.exercises[0]!.sets![0]!.isCompleted).toBe(false);
    });

    it('is a no-op when there is no active exercise', () => {
      const state = createInitialState([], 0, mkSettings());
      const next = apply(state, { type: 'ADD_SET' });
      expect(next.exercises).toHaveLength(0);
    });
  });

  // ============================================================
  // FINALIZE_WORKOUT
  // ============================================================
  describe('FINALIZE_WORKOUT', () => {
    it('sets finalized to true', () => {
      expect(baseState.finalized).toBe(false);
      const next = apply(baseState, { type: 'FINALIZE_WORKOUT' });
      expect(next.finalized).toBe(true);
    });
  });

  // ============================================================
  // SUPERSET ROUND LOGIC
  // ============================================================
  describe('COMPLETE_SET — superset rounds', () => {
    // Exercise with `count` uncompleted sets.
    const mkMulti = (id: string, name: string, count: number): Exercise => ({
      id,
      name,
      sets: Array.from({ length: count }, (_, i) => ({
        id: `${id}-s${i + 1}`,
        setNumber: i + 1,
        reps: 10,
        weight: 50,
        rpe: null,
        isWarmup: false,
        isCompleted: false,
        notes: '',
        completedAt: null,
      })),
    });

    it('advances to next exercise in group (not last) with short transition rest', () => {
      const exercises = [mkMulti('ex-1', 'Bench', 1), mkMulti('ex-2', 'Row', 1)];
      const state = createInitialState(exercises, 0, mkSettings({ autoAddSets: false }));
      state.supersetGroups = [{ id: 'ss-1', exercises: ['ex-1', 'ex-2'], restBetweenRounds: 90 }];
      state.currentExerciseIndex = 0;

      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.currentExerciseIndex).toBe(1);
      expect(next.restTimer.totalTime).toBe(15); // SUPERSET_TRANSITION_REST
    });

    it('runs a full 2-exercise superset across 2 rounds, returning to the first', () => {
      const exercises = [mkMulti('ex-1', 'A', 2), mkMulti('ex-2', 'B', 2)];
      const state = createInitialState(exercises, 0, mkSettings({ autoAddSets: false }));
      state.supersetGroups = [{ id: 'ss', exercises: ['ex-1', 'ex-2'], restBetweenRounds: 90 }];
      state.currentExerciseIndex = 0;

      // R1: A set1 → advance to B, short transition rest
      let s = apply(state, { type: 'COMPLETE_SET' });
      expect(s.currentExerciseIndex).toBe(1);
      expect(s.restTimer.totalTime).toBe(15);

      // R1: B set1 → wrap back to A (set2 still open) → NEW ROUND → round rest
      s = apply(s, { type: 'COMPLETE_SET' });
      expect(s.currentExerciseIndex).toBe(0);
      expect(s.restTimer.totalTime).toBe(90);

      // R2: A set2 → advance to B (set2 open) → transition rest
      s = apply(s, { type: 'COMPLETE_SET' });
      expect(s.currentExerciseIndex).toBe(1);
      expect(s.restTimer.totalTime).toBe(15);

      // R2: B set2 → group fully done → no advance, normal rest (default 60)
      s = apply(s, { type: 'COMPLETE_SET' });
      expect(s.currentExerciseIndex).toBe(1);
      expect(s.restTimer.totalTime).toBe(60);
    });

    it('cycles a 3-exercise giant set then stops when the group is done', () => {
      const exercises = [mkMulti('ex-1', 'A', 1), mkMulti('ex-2', 'B', 1), mkMulti('ex-3', 'C', 1)];
      const state = createInitialState(exercises, 0, mkSettings({ autoAddSets: false }));
      state.supersetGroups = [
        { id: 'gs', exercises: ['ex-1', 'ex-2', 'ex-3'], restBetweenRounds: 120 },
      ];
      state.currentExerciseIndex = 0;

      let s = apply(state, { type: 'COMPLETE_SET' }); // A → B
      expect(s.currentExerciseIndex).toBe(1);
      expect(s.restTimer.totalTime).toBe(15);

      s = apply(s, { type: 'COMPLETE_SET' }); // B → C
      expect(s.currentExerciseIndex).toBe(2);
      expect(s.restTimer.totalTime).toBe(15);

      s = apply(s, { type: 'COMPLETE_SET' }); // C → group done
      expect(s.currentExerciseIndex).toBe(2);
      expect(s.restTimer.totalTime).toBe(60);
    });
  });

  // ============================================================
  // COMPLETE_SET — autoAdvanceExercise
  // ============================================================
  describe('COMPLETE_SET — autoAdvanceExercise', () => {
    it('advances to the next exercise with open sets once the current one is done', () => {
      const exercises = [mkExercise({ id: 'ex-1' }), mkExercise({ id: 'ex-2' })];
      const state = createInitialState(
        exercises,
        0,
        mkSettings({ autoAddSets: false, autoAdvanceExercise: true })
      );
      state.currentExerciseIndex = 0;
      const next = apply(state, { type: 'COMPLETE_SET' }); // completes ex-1's only set
      expect(next.currentExerciseIndex).toBe(1);
    });

    it('does not advance when no other exercise has open sets', () => {
      const ex1 = mkExercise({ id: 'ex-1' });
      const ex2 = mkExercise({ id: 'ex-2' });
      ex2.sets![0]!.completedAt = new Date().toISOString();
      ex2.sets![0]!.isCompleted = true;
      const state = createInitialState(
        [ex1, ex2],
        0,
        mkSettings({ autoAddSets: false, autoAdvanceExercise: true })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.currentExerciseIndex).toBe(0);
    });

    it('stays put when autoAdvanceExercise is off', () => {
      const exercises = [mkExercise({ id: 'ex-1' }), mkExercise({ id: 'ex-2' })];
      const state = createInitialState(
        exercises,
        0,
        mkSettings({ autoAddSets: false, autoAdvanceExercise: false })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.currentExerciseIndex).toBe(0);
    });

    it('does not auto-advance in legacy autoAddSets mode (exercise never "done")', () => {
      const exercises = [mkExercise({ id: 'ex-1' }), mkExercise({ id: 'ex-2' })];
      const state = createInitialState(
        exercises,
        0,
        mkSettings({ autoAddSets: true, autoAdvanceExercise: true })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      // A fresh set was appended to ex-1, so it isn't complete → no advance.
      expect(next.currentExerciseIndex).toBe(0);
      expect(next.exercises[0]!.sets!).toHaveLength(2);
    });
  });

  // ============================================================
  // CREATE_SUPERSET — validation & overlap
  // ============================================================
  describe('CREATE_SUPERSET', () => {
    const threeExercises = (): Exercise[] => [
      mkExercise({ id: 'ex-1', name: 'A' }),
      mkExercise({ id: 'ex-2', name: 'B' }),
      mkExercise({ id: 'ex-3', name: 'C' }),
    ];

    it('creates a giant set with 3 exercises, de-duping ids', () => {
      const state = createInitialState(threeExercises(), 0, mkSettings());
      const next = apply(state, {
        type: 'CREATE_SUPERSET',
        payload: { exerciseIds: ['ex-1', 'ex-2', 'ex-2', 'ex-3'] },
      });
      expect(next.supersetGroups).toHaveLength(1);
      expect(next.supersetGroups[0]!.exercises).toEqual(['ex-1', 'ex-2', 'ex-3']);
    });

    it('is a no-op when fewer than 2 valid exercises remain', () => {
      const state = createInitialState([mkExercise({ id: 'ex-1' })], 0, mkSettings());
      const next = apply(state, {
        type: 'CREATE_SUPERSET',
        payload: { exerciseIds: ['ex-1', 'ghost'] },
      });
      expect(next.supersetGroups).toHaveLength(0);
    });

    it('removes overlapping exercises from a prior group, dropping it if degenerate', () => {
      const state = createInitialState(threeExercises(), 0, mkSettings());
      state.supersetGroups = [{ id: 'old', exercises: ['ex-1', 'ex-2'], restBetweenRounds: 60 }];
      // New group reuses ex-2 → old group loses ex-2 → only ex-1 left (<2) → dropped
      const next = apply(state, {
        type: 'CREATE_SUPERSET',
        payload: { exerciseIds: ['ex-2', 'ex-3'] },
      });
      expect(next.supersetGroups).toHaveLength(1);
      expect(next.supersetGroups[0]!.exercises).toEqual(['ex-2', 'ex-3']);
    });
  });

  // ============================================================
  // REMOVE_EXERCISE — index remap + superset-group cleanup
  // ============================================================
  describe('REMOVE_EXERCISE', () => {
    const threeExercises = (): Exercise[] => [
      mkExercise({ id: 'ex-1', name: 'A' }),
      mkExercise({ id: 'ex-2', name: 'B' }),
      mkExercise({ id: 'ex-3', name: 'C' }),
    ];

    it('decrements currentExerciseIndex when deleting an exercise before the active one', () => {
      // Arrange — 3 exercises, user mid-set on B (index 1)
      const state = createInitialState(threeExercises(), 0, mkSettings());
      state.currentExerciseIndex = 1;

      // Act — delete A (index 0)
      const next = apply(state, { type: 'REMOVE_EXERCISE', payload: 0 });

      // Assert — index follows B to its new position (0), not C
      expect(next.exercises.map((e) => e.id)).toEqual(['ex-2', 'ex-3']);
      expect(next.currentExerciseIndex).toBe(0);
      expect(next.exercises[next.currentExerciseIndex]!.id).toBe('ex-2');
    });

    it('leaves currentExerciseIndex unchanged when deleting an exercise after the active one', () => {
      const state = createInitialState(threeExercises(), 0, mkSettings());
      state.currentExerciseIndex = 0; // active = A

      const next = apply(state, { type: 'REMOVE_EXERCISE', payload: 2 }); // delete C

      expect(next.currentExerciseIndex).toBe(0);
      expect(next.exercises[next.currentExerciseIndex]!.id).toBe('ex-1');
    });

    it('clamps currentExerciseIndex when the active exercise itself is deleted (last position)', () => {
      const state = createInitialState(threeExercises(), 0, mkSettings());
      state.currentExerciseIndex = 2; // active = C (last)

      const next = apply(state, { type: 'REMOVE_EXERCISE', payload: 2 }); // delete C

      expect(next.exercises).toHaveLength(2);
      expect(next.currentExerciseIndex).toBe(1); // clamped to new last
    });

    it('prunes the removed exercise id from its superset group', () => {
      const state = createInitialState(threeExercises(), 0, mkSettings());
      state.supersetGroups = [
        { id: 'gs', exercises: ['ex-1', 'ex-2', 'ex-3'], restBetweenRounds: 90 },
      ];

      const next = apply(state, { type: 'REMOVE_EXERCISE', payload: 1 }); // delete B

      expect(next.supersetGroups).toHaveLength(1);
      expect(next.supersetGroups[0]!.exercises).toEqual(['ex-1', 'ex-3']);
    });

    it('drops a 2-member superset group that becomes degenerate after removal', () => {
      const state = createInitialState(threeExercises(), 0, mkSettings());
      state.supersetGroups = [{ id: 'ss', exercises: ['ex-1', 'ex-2'], restBetweenRounds: 60 }];

      const next = apply(state, { type: 'REMOVE_EXERCISE', payload: 0 }); // delete A

      // Only ex-2 would remain in the group (<2) → group dropped entirely.
      expect(next.supersetGroups).toHaveLength(0);
    });

    it('leaves unrelated superset groups untouched', () => {
      const state = createInitialState(threeExercises(), 0, mkSettings());
      state.supersetGroups = [{ id: 'ss', exercises: ['ex-2', 'ex-3'], restBetweenRounds: 60 }];

      const next = apply(state, { type: 'REMOVE_EXERCISE', payload: 0 }); // delete A (not in group)

      expect(next.supersetGroups).toHaveLength(1);
      expect(next.supersetGroups[0]!.exercises).toEqual(['ex-2', 'ex-3']);
    });
  });

  // ============================================================
  // REORDER_EXERCISES — keep the active exercise by identity
  // ============================================================
  describe('REORDER_EXERCISES', () => {
    const threeExercises = (): Exercise[] => [
      mkExercise({ id: 'ex-1', name: 'A' }),
      mkExercise({ id: 'ex-2', name: 'B' }),
      mkExercise({ id: 'ex-3', name: 'C' }),
    ];

    it('remaps currentExerciseIndex so the active exercise stays the same after a drag-reorder', () => {
      // Arrange — active = B (index 1)
      const state = createInitialState(threeExercises(), 0, mkSettings());
      state.currentExerciseIndex = 1;

      // Act — drag B to the front: [B, A, C]
      const reordered = [
        mkExercise({ id: 'ex-2', name: 'B' }),
        mkExercise({ id: 'ex-1', name: 'A' }),
        mkExercise({ id: 'ex-3', name: 'C' }),
      ];
      const next = apply(state, { type: 'REORDER_EXERCISES', payload: reordered });

      // Assert — index now points at B's new slot (0), not whatever landed at 1
      expect(next.currentExerciseIndex).toBe(0);
      expect(next.exercises[next.currentExerciseIndex]!.id).toBe('ex-2');
    });

    it('clamps the index when the active exercise is dropped by the name filter', () => {
      // Arrange — active = C (index 2)
      const state = createInitialState(threeExercises(), 0, mkSettings());
      state.currentExerciseIndex = 2;

      // Act — C gets an empty name (dropped by filter): [A, B]
      const reordered = [
        mkExercise({ id: 'ex-1', name: 'A' }),
        mkExercise({ id: 'ex-2', name: 'B' }),
        mkExercise({ id: 'ex-3', name: '   ' }),
      ];
      const next = apply(state, { type: 'REORDER_EXERCISES', payload: reordered });

      // Assert — array shrank to 2; index clamped into bounds (still resolves a card)
      expect(next.exercises).toHaveLength(2);
      expect(next.currentExerciseIndex).toBeLessThan(next.exercises.length);
      expect(next.exercises[next.currentExerciseIndex]).toBeDefined();
    });
  });

  // ============================================================
  // UNDO_LAST_SET
  // ============================================================
  describe('UNDO_LAST_SET', () => {
    it('clears completedAt and isCompleted on the last completed set', () => {
      let state = apply(baseState, { type: 'COMPLETE_SET' });
      state = apply(state, { type: 'UNDO_LAST_SET' });
      const set = state.exercises[0]!.sets![0]!;
      expect(set.isCompleted).toBe(false);
      expect(set.completedAt).toBeNull();
    });

    it('removes auto-generated orphan set after undo', () => {
      let state = apply(baseState, { type: 'COMPLETE_SET' });
      expect(state.exercises[0]!.sets!).toHaveLength(2);
      state = apply(state, { type: 'UNDO_LAST_SET' });
      expect(state.exercises[0]!.sets!).toHaveLength(1);
    });

    it('stops rest timer on undo', () => {
      let state = apply(baseState, { type: 'COMPLETE_SET' });
      expect(state.restTimer.active).toBe(true);
      state = apply(state, { type: 'UNDO_LAST_SET' });
      expect(state.restTimer.active).toBe(false);
    });

    it('clears pendingHaptic and showConfetti on undo', () => {
      const s = createInitialState(
        [mkExercise()],
        0,
        mkSettings({ hapticsEnabled: true, prCelebrationIntensity: 'full' })
      );
      let state = apply(s, { type: 'COMPLETE_SET' });
      state = apply(state, { type: 'UNDO_LAST_SET' });
      expect(state.pendingHaptic).toBeNull();
      expect(state.showConfetti).toBe(false);
    });

    it('is a no-op when no sets are completed', () => {
      const next = apply(baseState, { type: 'UNDO_LAST_SET' });
      expect(next.exercises[0]!.sets!).toHaveLength(1);
      expect(next.exercises[0]!.sets![0]!.isCompleted).toBe(false);
    });

    it('does not remove a non-auto-generated next set with data', () => {
      const ex = mkExercise();
      ex.sets = [
        {
          id: 's1',
          setNumber: 1,
          reps: 10,
          weight: 80,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
        },
        {
          id: 's2',
          setNumber: 2,
          reps: 8,
          weight: 85,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
        },
      ];
      const state = createInitialState([ex], 0, mkSettings());
      // Complete first set
      let next = apply(state, { type: 'COMPLETE_SET' });
      // Undo — should NOT remove s2 because it has data (reps=8, weight=85)
      next = apply(next, { type: 'UNDO_LAST_SET' });
      expect(next.exercises[0]!.sets!).toHaveLength(2);
    });
  });

  // ============================================================
  // TOGGLE_PAUSE
  // ============================================================
  describe('TOGGLE_PAUSE', () => {
    it('toggles isPaused from false to true', () => {
      const next = apply(baseState, { type: 'TOGGLE_PAUSE' });
      expect(next.isPaused).toBe(true);
      expect(next.lastPauseTimestamp).toBe(Date.now());
    });

    it('toggles isPaused from true to false and accumulates paused time', () => {
      let state = apply(baseState, { type: 'TOGGLE_PAUSE' });
      vi.advanceTimersByTime(5000);
      state = apply(state, { type: 'TOGGLE_PAUSE' });
      expect(state.isPaused).toBe(false);
      expect(state.totalPausedTime).toBe(5000);
      expect(state.lastPauseTimestamp).toBeNull();
    });

    it('freezes rest timer endTime as negative remaining ms on pause', () => {
      // Start rest timer
      let state = apply(baseState, { type: 'COMPLETE_SET' });
      expect(state.restTimer.active).toBe(true);
      const endTime = state.restTimer.endTime!;

      vi.advanceTimersByTime(10000); // 10s pass
      state = apply(state, { type: 'TOGGLE_PAUSE' });

      // endTime should be negative (frozen remaining ms)
      const expectedRemaining = endTime - Date.now(); // should be 50000
      expect(state.restTimer.endTime).toBe(-expectedRemaining);
      expect(state.restTimer.endTime!).toBeLessThanOrEqual(0);
    });

    it('thaws rest timer with fresh absolute endTime on resume', () => {
      let state = apply(baseState, { type: 'COMPLETE_SET' });
      vi.advanceTimersByTime(10000);
      state = apply(state, { type: 'TOGGLE_PAUSE' }); // freeze
      const frozenRemaining = -state.restTimer.endTime!;

      vi.advanceTimersByTime(30000); // 30s paused
      state = apply(state, { type: 'TOGGLE_PAUSE' }); // thaw

      expect(state.restTimer.endTime).toBe(Date.now() + frozenRemaining);
      expect(state.restTimer.endTime!).toBeGreaterThan(0);
    });
  });

  // ============================================================
  // NUMPAD_SUBMIT
  // ============================================================
  describe('NUMPAD_SUBMIT', () => {
    it('sets weight on the active set from numpad value', () => {
      const state = structuredClone(baseState);
      state.numpad = { isOpen: true, target: 'weight', value: '100' };
      const next = apply(state, { type: 'NUMPAD_SUBMIT' });
      expect(next.exercises[0]!.sets![0]!.weight).toBe(100);
      expect(next.numpad.isOpen).toBe(false);
    });

    it('sets reps as rounded integer', () => {
      const state = structuredClone(baseState);
      state.numpad = { isOpen: true, target: 'reps', value: '8.7' };
      const next = apply(state, { type: 'NUMPAD_SUBMIT' });
      expect(next.exercises[0]!.sets![0]!.reps).toBe(9);
    });

    it('clamps reps to 0 minimum', () => {
      const state = structuredClone(baseState);
      state.numpad = { isOpen: true, target: 'reps', value: '-5' };
      const next = apply(state, { type: 'NUMPAD_SUBMIT' });
      expect(next.exercises[0]!.sets![0]!.reps).toBe(0);
    });

    it('ignores NaN numpad value', () => {
      const state = structuredClone(baseState);
      state.numpad = { isOpen: true, target: 'weight', value: 'abc' };
      const next = apply(state, { type: 'NUMPAD_SUBMIT' });
      expect(next.exercises[0]!.sets![0]!.weight).toBe(80);
    });

    it('is a no-op when target is null', () => {
      const state = structuredClone(baseState);
      state.numpad = { isOpen: true, target: null, value: '100' };
      const next = apply(state, { type: 'NUMPAD_SUBMIT' });
      expect(next.exercises[0]!.sets![0]!.weight).toBe(80);
    });
  });

  // ============================================================
  // EDGE CASES
  // ============================================================
  describe('edge cases', () => {
    it('COMPLETE_SET with empty exercises array is a no-op', () => {
      const state = createInitialState([], 0, mkSettings());
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.exercises).toHaveLength(0);
    });

    it('UNDO_LAST_SET with empty exercises array is a no-op', () => {
      const state = createInitialState([], 0, mkSettings());
      const next = apply(state, { type: 'UNDO_LAST_SET' });
      expect(next.exercises).toHaveLength(0);
    });

    it('completedAt and isCompleted stay in sync across multiple complete/undo cycles', () => {
      let state = baseState;
      // Complete
      state = apply(state, { type: 'COMPLETE_SET' });
      expect(state.exercises[0]!.sets![0]!.isCompleted).toBe(true);
      expect(state.exercises[0]!.sets![0]!.completedAt).not.toBeNull();
      // Undo
      state = apply(state, { type: 'UNDO_LAST_SET' });
      expect(state.exercises[0]!.sets![0]!.isCompleted).toBe(false);
      expect(state.exercises[0]!.sets![0]!.completedAt).toBeNull();
      // Complete again
      state = apply(state, { type: 'COMPLETE_SET' });
      expect(state.exercises[0]!.sets![0]!.isCompleted).toBe(true);
      expect(state.exercises[0]!.sets![0]!.completedAt).not.toBeNull();
    });

    it('timed exercise creates next set with duration inherited', () => {
      const ex = mkExercise({ isTimed: true });
      ex.sets = [
        {
          id: 's1',
          setNumber: 1,
          reps: 0,
          weight: 0,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
          duration: 30,
        },
      ];
      const state = createInitialState([ex], 0, mkSettings());
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.exercises[0]!.sets![1]!.duration).toBe(30);
      expect(next.exercises[0]!.sets![1]!.reps).toBe(0);
    });
  });

  // ============================================================
  // EDIT_SPECIFIC_SET
  // ============================================================
  describe('EDIT_SPECIFIC_SET', () => {
    it('updates weight and reps of a specific set on the targeted exercise', () => {
      // Arrange
      const next = apply(baseState, {
        type: 'EDIT_SPECIFIC_SET',
        payload: { exerciseIndex: 0, setIndex: 0, updates: { weight: 100, reps: 12 } },
      });

      // Assert
      expect(next.exercises[0]!.sets![0]!.weight).toBe(100);
      expect(next.exercises[0]!.sets![0]!.reps).toBe(12);
    });

    it('edits a set on another exercise even when currentExerciseIndex is invalid', () => {
      // Arrange — two exercises, currentExerciseIndex points nowhere valid
      const exercises: Exercise[] = [
        mkExercise({ id: 'ex-1', name: 'Bench' }),
        mkExercise({ id: 'ex-2', name: 'Row' }),
      ];
      const state = createInitialState(exercises, 0, mkSettings());
      state.currentExerciseIndex = 99; // invalid — no active exercise

      // Act — edit set on exercise index 1 via payload
      const next = apply(state, {
        type: 'EDIT_SPECIFIC_SET',
        payload: { exerciseIndex: 1, setIndex: 0, updates: { weight: 50 } },
      });

      // Assert — the targeted set was updated despite invalid current index
      expect(next.exercises[1]!.sets![0]!.weight).toBe(50);
    });

    it('is a no-op when the target exercise does not exist', () => {
      const next = apply(baseState, {
        type: 'EDIT_SPECIFIC_SET',
        payload: { exerciseIndex: 5, setIndex: 0, updates: { weight: 100 } },
      });
      expect(next.exercises[0]!.sets![0]!.weight).toBe(80);
    });

    it('is a no-op when the target set does not exist', () => {
      const next = apply(baseState, {
        type: 'EDIT_SPECIFIC_SET',
        payload: { exerciseIndex: 0, setIndex: 9, updates: { weight: 100 } },
      });
      expect(next.exercises[0]!.sets![0]!.weight).toBe(80);
    });

    it('only updates provided fields, leaving others untouched', () => {
      const next = apply(baseState, {
        type: 'EDIT_SPECIFIC_SET',
        payload: { exerciseIndex: 0, setIndex: 0, updates: { reps: 5 } },
      });
      expect(next.exercises[0]!.sets![0]!.reps).toBe(5);
      expect(next.exercises[0]!.sets![0]!.weight).toBe(80); // unchanged
    });
  });

  // ============================================================
  // DELETE_SET
  // ============================================================
  describe('DELETE_SET', () => {
    it('removes the targeted set when more than one set exists', () => {
      // Arrange — exercise with two sets
      const ex = mkExercise();
      ex.sets = [
        {
          id: 's1',
          setNumber: 1,
          reps: 10,
          weight: 80,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
        },
        {
          id: 's2',
          setNumber: 2,
          reps: 8,
          weight: 85,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
        },
      ];
      const state = createInitialState([ex], 0, mkSettings());

      // Act
      const next = apply(state, {
        type: 'DELETE_SET',
        payload: { exerciseIndex: 0, setIndex: 0 },
      });

      // Assert — only the second set remains
      expect(next.exercises[0]!.sets!).toHaveLength(1);
      expect(next.exercises[0]!.sets![0]!.id).toBe('s2');
    });

    it('deletes a set on another exercise even when currentExerciseIndex is invalid', () => {
      const ex2 = mkExercise({ id: 'ex-2', name: 'Row' });
      ex2.sets = [
        { ...ex2.sets![0]!, id: 'r1', setNumber: 1 },
        { ...ex2.sets![0]!, id: 'r2', setNumber: 2 },
      ];
      const exercises: Exercise[] = [mkExercise({ id: 'ex-1', name: 'Bench' }), ex2];
      const state = createInitialState(exercises, 0, mkSettings());
      state.currentExerciseIndex = -1; // invalid — no active exercise

      const next = apply(state, {
        type: 'DELETE_SET',
        payload: { exerciseIndex: 1, setIndex: 0 },
      });

      expect(next.exercises[1]!.sets!).toHaveLength(1);
      expect(next.exercises[1]!.sets![0]!.id).toBe('r2');
    });

    it('does not delete the last remaining set', () => {
      const next = apply(baseState, {
        type: 'DELETE_SET',
        payload: { exerciseIndex: 0, setIndex: 0 },
      });
      expect(next.exercises[0]!.sets!).toHaveLength(1);
    });

    it('is a no-op when the target exercise does not exist', () => {
      const next = apply(baseState, {
        type: 'DELETE_SET',
        payload: { exerciseIndex: 5, setIndex: 0 },
      });
      expect(next.exercises[0]!.sets!).toHaveLength(1);
    });
  });

  // ============================================================
  // ADD_REST_TIME
  // ============================================================
  describe('ADD_REST_TIME', () => {
    it('extends an active timer by adjusting the absolute endTime', () => {
      // Arrange — active rest timer ending 60s from now
      const state = structuredClone(baseState);
      state.restTimer = {
        active: true,
        endTime: Date.now() + 60000,
        totalTime: 60,
        timeLeft: 60,
      };

      // Act — add 30 seconds
      const next = apply(state, { type: 'ADD_REST_TIME', payload: 30 });

      // Assert — endTime pushed out by 30s
      expect(next.restTimer.endTime).toBe(state.restTimer.endTime! + 30000);
    });

    it('clamps a shrunk active timer to at least 1s in the future', () => {
      const state = structuredClone(baseState);
      state.restTimer = {
        active: true,
        endTime: Date.now() + 2000,
        totalTime: 2,
        timeLeft: 2,
      };
      // Subtract 30s — would go into the past, must clamp to now+1000
      const next = apply(state, { type: 'ADD_REST_TIME', payload: -30 });
      expect(next.restTimer.endTime).toBe(Date.now() + 1000);
    });

    it('extends a frozen (paused) timer by adjusting the negative remaining', () => {
      // Arrange — paused timer: endTime encodes -remainingMs (50s left)
      const state = structuredClone(baseState);
      state.restTimer = {
        active: true,
        endTime: -50000,
        totalTime: 60,
        timeLeft: 50,
      };

      // Act — add 30 seconds
      const next = apply(state, { type: 'ADD_REST_TIME', payload: 30 });

      // Assert — magnitude grows to 80s, kept negative, timeLeft synced
      expect(next.restTimer.endTime).toBe(-80000);
      expect(next.restTimer.timeLeft).toBe(80);
    });

    it('is a no-op when there is no active endTime', () => {
      const state = structuredClone(baseState); // endTime null by default
      const next = apply(state, { type: 'ADD_REST_TIME', payload: 30 });
      expect(next.restTimer.endTime).toBeNull();
    });
  });

  // ============================================================
  // SYNC_REST_TIMER — rest-timer-end branch
  // ============================================================
  describe('SYNC_REST_TIMER', () => {
    it('clears active and sets pendingHaptic=REST_END when the timer has elapsed', () => {
      // Arrange — active timer whose endTime is already in the past
      const state = createInitialState([mkExercise()], 0, mkSettings({ hapticsEnabled: true }));
      state.restTimer = {
        active: true,
        endTime: Date.now() - 1000, // elapsed
        totalTime: 60,
        timeLeft: 1,
      };

      // Act
      const next = apply(state, { type: 'SYNC_REST_TIMER' });

      // Assert — timer cleared and REST_END haptic queued
      expect(next.restTimer.active).toBe(false);
      expect(next.restTimer.endTime).toBeNull();
      expect(next.restTimer.timeLeft).toBe(0);
      expect(next.pendingHaptic).toBe('REST_END');
    });

    it('does not set pendingHaptic when haptics are disabled', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ hapticsEnabled: false }));
      state.restTimer = {
        active: true,
        endTime: Date.now() - 1000,
        totalTime: 60,
        timeLeft: 1,
      };
      const next = apply(state, { type: 'SYNC_REST_TIMER' });
      expect(next.restTimer.active).toBe(false);
      expect(next.pendingHaptic).toBeNull();
    });

    it('updates timeLeft without ending when the timer is still running', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ hapticsEnabled: true }));
      state.restTimer = {
        active: true,
        endTime: Date.now() + 30000,
        totalTime: 60,
        timeLeft: 60,
      };
      const next = apply(state, { type: 'SYNC_REST_TIMER' });
      expect(next.restTimer.active).toBe(true);
      expect(next.restTimer.timeLeft).toBe(30);
      expect(next.pendingHaptic).toBeNull();
    });

    it('does not tick down a frozen (paused) timer', () => {
      const state = createInitialState([mkExercise()], 0, mkSettings({ hapticsEnabled: true }));
      state.isPaused = true;
      state.restTimer = {
        active: true,
        endTime: -40000, // frozen 40s remaining
        totalTime: 60,
        timeLeft: 40,
      };
      const next = apply(state, { type: 'SYNC_REST_TIMER' });
      expect(next.restTimer.active).toBe(true);
      expect(next.restTimer.endTime).toBe(-40000);
      expect(next.pendingHaptic).toBeNull();
    });
  });

  // ============================================================
  // SHOW_PR_CELEBRATION — confetti gated on an actual PR
  // ============================================================
  describe('SHOW_PR_CELEBRATION', () => {
    it('shows confetti on a real PR when intensity is full', () => {
      const state = createInitialState(
        [mkExercise()],
        0,
        mkSettings({ prCelebrationIntensity: 'full' })
      );
      // biome-ignore lint/suspicious/noExplicitAny: minimal PR payload for test
      const pr = { exerciseName: 'Bench Press', type: 'weight', value: 100 } as any;
      const next = apply(state, { type: 'SHOW_PR_CELEBRATION', payload: pr });
      expect(next.showPRCelebration).toEqual(pr);
      expect(next.showConfetti).toBe(true);
    });

    it('does not show confetti on a PR when intensity is subtle', () => {
      const state = createInitialState(
        [mkExercise()],
        0,
        mkSettings({ prCelebrationIntensity: 'subtle' })
      );
      // biome-ignore lint/suspicious/noExplicitAny: minimal PR payload for test
      const pr = { exerciseName: 'Bench Press', type: 'weight', value: 100 } as any;
      const next = apply(state, { type: 'SHOW_PR_CELEBRATION', payload: pr });
      expect(next.showPRCelebration).toEqual(pr);
      expect(next.showConfetti).toBe(false);
    });

    it('COMPLETE_SET alone does not trigger confetti (no PR)', () => {
      // Regression: confetti must NOT fire on every completed set, even at full intensity
      const state = createInitialState(
        [mkExercise()],
        0,
        mkSettings({ prCelebrationIntensity: 'full' })
      );
      const next = apply(state, { type: 'COMPLETE_SET' });
      expect(next.showConfetti).toBe(false);
    });
  });

  // ============================================================
  // DELETE_SET undo buffer + RESTORE_DELETED_SET
  // ============================================================
  describe('DELETE_SET + RESTORE_DELETED_SET (undo)', () => {
    const twoSets = (): Exercise =>
      mkExercise({
        sets: [
          {
            id: 'set-1',
            setNumber: 1,
            reps: 10,
            weight: 80,
            rpe: null,
            isWarmup: false,
            isCompleted: false,
            notes: '',
            completedAt: null,
          },
          {
            id: 'set-2',
            setNumber: 2,
            reps: 8,
            weight: 85,
            rpe: null,
            isWarmup: false,
            isCompleted: false,
            notes: '',
            completedAt: null,
          },
        ],
      });

    it('snapshots the deleted set into lastDeletedSet', () => {
      const state = createInitialState([twoSets()], 0, mkSettings());
      const next = apply(state, { type: 'DELETE_SET', payload: { exerciseIndex: 0, setIndex: 0 } });
      expect(next.exercises[0]?.sets).toHaveLength(1);
      expect(next.lastDeletedSet?.set.id).toBe('set-1');
      expect(next.lastDeletedSet?.setIndex).toBe(0);
    });

    it('restores the deleted set at its original index and consumes the buffer', () => {
      const state = createInitialState([twoSets()], 0, mkSettings());
      const deleted = apply(state, {
        type: 'DELETE_SET',
        payload: { exerciseIndex: 0, setIndex: 0 },
      });
      const restored = apply(deleted, { type: 'RESTORE_DELETED_SET' });
      expect(restored.exercises[0]?.sets?.map((s) => s.id)).toEqual(['set-1', 'set-2']);
      expect(restored.lastDeletedSet).toBeNull();
    });

    it('RESTORE_DELETED_SET is a no-op when nothing was deleted', () => {
      const next = apply(baseState, { type: 'RESTORE_DELETED_SET' });
      expect(next.exercises[0]?.sets).toHaveLength(1);
      expect(next.lastDeletedSet).toBeNull();
    });

    it('does not snapshot when deleting the last remaining set is refused', () => {
      const next = apply(baseState, {
        type: 'DELETE_SET',
        payload: { exerciseIndex: 0, setIndex: 0 },
      });
      expect(next.exercises[0]?.sets).toHaveLength(1);
      expect(next.lastDeletedSet).toBeNull();
    });

    it('stores the delete token in the snapshot and restores on a matching token', () => {
      const state = createInitialState([twoSets()], 0, mkSettings());
      const deleted = apply(state, {
        type: 'DELETE_SET',
        payload: { exerciseIndex: 0, setIndex: 0, token: 'tok-1' },
      });
      expect(deleted.lastDeletedSet?.token).toBe('tok-1');

      const restored = apply(deleted, {
        type: 'RESTORE_DELETED_SET',
        payload: { token: 'tok-1' },
      });
      expect(restored.exercises[0]?.sets?.map((s) => s.id)).toEqual(['set-1', 'set-2']);
      expect(restored.lastDeletedSet).toBeNull();
    });

    it('refuses to restore when the undo token belongs to an older deletion', () => {
      // Delete set-1 (token A), then set-2 of the restored... simulate two
      // sequential deletes: the second overwrites the snapshot. An undo from
      // the FIRST toast (token A) must NOT resurrect the second snapshot.
      const state = createInitialState([twoSets()], 0, mkSettings());
      const afterFirst = apply(state, {
        type: 'DELETE_SET',
        payload: { exerciseIndex: 0, setIndex: 0, token: 'tok-A' },
      });
      // Add a set so a second delete is allowed (last-set guard), then delete it.
      const withExtra = apply(afterFirst, { type: 'ADD_SET' });
      const afterSecond = apply(withExtra, {
        type: 'DELETE_SET',
        payload: { exerciseIndex: 0, setIndex: 0, token: 'tok-B' },
      });
      expect(afterSecond.lastDeletedSet?.token).toBe('tok-B');
      const setsBefore = afterSecond.exercises[0]?.sets?.length;

      // Stale undo (token A) — no-op, snapshot intact.
      const staleUndo = apply(afterSecond, {
        type: 'RESTORE_DELETED_SET',
        payload: { token: 'tok-A' },
      });
      expect(staleUndo.exercises[0]?.sets?.length).toBe(setsBefore);
      expect(staleUndo.lastDeletedSet?.token).toBe('tok-B');
    });
  });

  // ============================================================
  // RESET_ACTIVE_WORKOUT (discard restored draft, start fresh)
  // ============================================================
  describe('RESET_ACTIVE_WORKOUT', () => {
    it('clears the draft in place and resets timing without finalizing', () => {
      const state = structuredClone(baseState);
      state.startTimestamp = Date.now() - 60 * 60 * 1000; // stale: an hour ago
      state.totalPausedTime = 120_000;
      state.isPaused = true;
      state.lastPauseTimestamp = Date.now() - 1000;
      state.restTimer = { active: true, endTime: Date.now() + 30000, totalTime: 60, timeLeft: 30 };

      const next = apply(state, { type: 'RESET_ACTIVE_WORKOUT' });

      expect(next.exercises).toEqual([]);
      expect(next.currentExerciseIndex).toBe(0);
      expect(next.supersetGroups).toEqual([]);
      expect(next.startTimestamp).toBe(Date.now());
      expect(next.totalPausedTime).toBe(0);
      expect(next.isPaused).toBe(false);
      expect(next.lastPauseTimestamp).toBeNull();
      expect(next.restTimer.active).toBe(false);
      expect(next.lastDeletedSet).toBeNull();
      // NOT finalized — the session continues with the new template.
      expect(next.finalized).toBe(false);
    });
  });

  // ============================================================
  // NUMPAD_CLEAR + NUMPAD_SUBMIT advance flow
  // ============================================================
  describe('NUMPAD_CLEAR + NUMPAD_SUBMIT advance', () => {
    it('NUMPAD_CLEAR empties the working value and keeps the numpad open', () => {
      let state = apply(baseState, { type: 'OPEN_NUMPAD', payload: 'weight' });
      state = apply(state, { type: 'SET_NUMPAD_VALUE', payload: '127.5' });
      const next = apply(state, { type: 'NUMPAD_CLEAR' });
      expect(next.numpad.value).toBe('');
      expect(next.numpad.isOpen).toBe(true);
    });

    it('NUMPAD_SUBMIT with advance writes the weight, re-targets reps, and stays open', () => {
      let state = apply(baseState, { type: 'OPEN_NUMPAD', payload: 'weight' });
      state = apply(state, { type: 'SET_NUMPAD_VALUE', payload: '90' });
      const next = apply(state, { type: 'NUMPAD_SUBMIT', payload: { advance: true } });
      expect(next.exercises[0]?.sets?.[0]?.weight).toBe(90);
      expect(next.numpad.isOpen).toBe(true);
      expect(next.numpad.target).toBe('reps');
      expect(next.numpad.value).toBe('');
    });

    it('NUMPAD_SUBMIT with advance from reps closes normally (advance is weight-only)', () => {
      let state = apply(baseState, { type: 'OPEN_NUMPAD', payload: 'reps' });
      state = apply(state, { type: 'SET_NUMPAD_VALUE', payload: '12' });
      const next = apply(state, { type: 'NUMPAD_SUBMIT', payload: { advance: true } });
      expect(next.exercises[0]?.sets?.[0]?.reps).toBe(12);
      expect(next.numpad.isOpen).toBe(false);
    });

    it('plain NUMPAD_SUBMIT (no payload) keeps the legacy close-on-submit behavior', () => {
      let state = apply(baseState, { type: 'OPEN_NUMPAD', payload: 'weight' });
      state = apply(state, { type: 'SET_NUMPAD_VALUE', payload: '100' });
      const next = apply(state, { type: 'NUMPAD_SUBMIT' });
      expect(next.exercises[0]?.sets?.[0]?.weight).toBe(100);
      expect(next.numpad.isOpen).toBe(false);
    });
  });

  // ============================================================
  // SWAP_EXERCISE — mid-workout movement swap (Task 1)
  // ============================================================
  describe('SWAP_EXERCISE', () => {
    const ORIG = 'לחיצת מוט בשיפוע 45° | 45° Incline Barbell Press';
    const ALT1 = 'לחיצת משקולות בשיפוע 45° | 45° Incline DB Press';
    const ALT2 = 'לחיצת חזה במכונה בשיפוע 45° | 45° Incline Machine Press';
    const mkProgramEx = (): Exercise =>
      mkExercise({
        id: 'ex-1',
        name: ORIG,
        exerciseName: ORIG,
        exerciseId: '45° Incline Barbell Press',
        programExtras: { rpeTarget: 8, restTime: 180, alternatives: [ALT1, ALT2] },
      });

    it('replaces the movement name + exerciseId, preserving sets and prescription', () => {
      const state = createInitialState([mkProgramEx()], 0, mkSettings());
      const next = apply(state, {
        type: 'SWAP_EXERCISE',
        payload: { exerciseId: 'ex-1', newName: ALT1 },
      });
      const ex = next.exercises[0]!;
      expect(ex.name).toBe(ALT1);
      expect(ex.exerciseName).toBe(ALT1);
      expect(ex.exerciseId).toBe('45° Incline DB Press'); // English side of the label
      // Prescription untouched — only the movement changed.
      expect(ex.programExtras?.rpeTarget).toBe(8);
      expect(ex.programExtras?.restTime).toBe(180);
      expect(ex.sets).toHaveLength(1);
    });

    it('moves the previous movement into alternatives and removes the chosen one (swap-back)', () => {
      const state = createInitialState([mkProgramEx()], 0, mkSettings());
      const next = apply(state, {
        type: 'SWAP_EXERCISE',
        payload: { exerciseId: 'ex-1', newName: ALT1 },
      });
      const alts = next.exercises[0]!.programExtras!.alternatives!;
      expect(alts).toContain(ORIG); // previous movement is now an alternative
      expect(alts).not.toContain(ALT1); // chosen movement removed from the list
      expect(alts).toContain(ALT2); // the other alternative is preserved
      expect(alts[0]).toBe(ORIG); // previous movement added to the FRONT
    });

    it('supports swapping back to the original', () => {
      const state = createInitialState([mkProgramEx()], 0, mkSettings());
      let next = apply(state, {
        type: 'SWAP_EXERCISE',
        payload: { exerciseId: 'ex-1', newName: ALT1 },
      });
      next = apply(next, { type: 'SWAP_EXERCISE', payload: { exerciseId: 'ex-1', newName: ORIG } });
      expect(next.exercises[0]!.name).toBe(ORIG);
      expect(next.exercises[0]!.exerciseId).toBe('45° Incline Barbell Press');
      expect(next.exercises[0]!.programExtras!.alternatives).toContain(ALT1);
    });

    it('is a no-op for an unknown exercise id', () => {
      const state = createInitialState([mkProgramEx()], 0, mkSettings());
      const next = apply(state, {
        type: 'SWAP_EXERCISE',
        payload: { exerciseId: 'ghost', newName: ALT1 },
      });
      expect(next.exercises[0]!.name).toBe(ORIG);
    });

    it('is a no-op when swapping to the same movement', () => {
      const state = createInitialState([mkProgramEx()], 0, mkSettings());
      const next = apply(state, {
        type: 'SWAP_EXERCISE',
        payload: { exerciseId: 'ex-1', newName: ORIG },
      });
      expect(next.exercises[0]!.name).toBe(ORIG);
      expect(next.exercises[0]!.programExtras!.alternatives).toEqual([ALT1, ALT2]);
    });

    it('refuses the swap once a working set is already logged (no history mis-attribution)', () => {
      const ex = mkProgramEx();
      ex.sets![0]!.completedAt = new Date().toISOString();
      ex.sets![0]!.isCompleted = true;
      const state = createInitialState([ex], 0, mkSettings());
      const next = apply(state, {
        type: 'SWAP_EXERCISE',
        payload: { exerciseId: 'ex-1', newName: ALT1 },
      });
      // Movement unchanged — the logged set still belongs to the original.
      expect(next.exercises[0]!.name).toBe(ORIG);
      expect(next.exercises[0]!.exerciseId).toBe('45° Incline Barbell Press');
    });

    it('still allows the swap when only a warmup has been completed', () => {
      const ex = mkProgramEx();
      ex.sets = [
        {
          id: 'w1',
          setNumber: 1,
          reps: 0,
          weight: 0,
          rpe: null,
          isWarmup: true,
          isCompleted: true,
          notes: '',
          completedAt: new Date().toISOString(),
        },
        {
          id: 's1',
          setNumber: 2,
          reps: 8,
          weight: 0,
          rpe: null,
          isWarmup: false,
          isCompleted: false,
          notes: '',
          completedAt: null,
        },
      ];
      const state = createInitialState([ex], 0, mkSettings());
      const next = apply(state, {
        type: 'SWAP_EXERCISE',
        payload: { exerciseId: 'ex-1', newName: ALT1 },
      });
      expect(next.exercises[0]!.name).toBe(ALT1);
    });
  });

  // ============================================================
  // COMPLETE_SET — carry weight forward (Task 5)
  // ============================================================
  describe('COMPLETE_SET — carry weight forward', () => {
    type TestSet = NonNullable<Exercise['sets']>[number];
    const mkSet = (overrides: Partial<TestSet> & { id: string; setNumber: number }): TestSet =>
      ({
        reps: 8,
        weight: 0,
        rpe: null,
        isWarmup: false,
        isCompleted: false,
        notes: '',
        completedAt: null,
        ...overrides,
      }) as TestSet;

    const mkEmptyWorking = (count: number): Exercise =>
      mkExercise({
        id: 'ex-1',
        name: 'Bench',
        sets: Array.from({ length: count }, (_, i) => mkSet({ id: `s${i + 1}`, setNumber: i + 1 })),
      });

    it('pre-fills the next empty set with the just-completed weight (not marked complete)', () => {
      const state = createInitialState([mkEmptyWorking(3)], 0, mkSettings({ autoAddSets: false }));
      let s = apply(state, { type: 'UPDATE_SET', payload: { field: 'weight', value: 60 } });
      s = apply(s, { type: 'COMPLETE_SET' });
      const sets = s.exercises[0]!.sets!;
      expect(sets[1]!.weight).toBe(60);
      expect(sets[1]!.completedAt).toBeNull();
      // Only the immediate next set is seeded — it cascades as each completes.
      expect(sets[2]!.weight).toBe(0);
    });

    it('does not overwrite a weight the user already entered on the next set', () => {
      const ex = mkEmptyWorking(2);
      ex.sets![1]!.weight = 100; // user pre-typed set 2
      const state = createInitialState([ex], 0, mkSettings({ autoAddSets: false }));
      let s = apply(state, { type: 'UPDATE_SET', payload: { field: 'weight', value: 60 } });
      s = apply(s, { type: 'COMPLETE_SET' });
      expect(s.exercises[0]!.sets![1]!.weight).toBe(100);
    });

    it('does not leak a working weight into a warmup set', () => {
      const ex = mkExercise({
        id: 'ex-1',
        name: 'Bench',
        sets: [
          mkSet({ id: 'w1', setNumber: 1, isWarmup: true, reps: 0 }),
          mkSet({ id: 's1', setNumber: 2, isWarmup: false }),
        ],
      });
      // Complete the warmup with a light weight; the working set must stay empty.
      const state = createInitialState([ex], 0, mkSettings({ autoAddSets: false }));
      let s = apply(state, { type: 'UPDATE_SET', payload: { field: 'weight', value: 20 } });
      s = apply(s, { type: 'COMPLETE_SET' });
      expect(s.exercises[0]!.sets![1]!.weight).toBe(0);
    });

    it('carries warmup→warmup but stops at the working boundary', () => {
      const ex = mkExercise({
        id: 'ex-1',
        name: 'Bench',
        sets: [
          mkSet({ id: 'w1', setNumber: 1, isWarmup: true, reps: 0 }),
          mkSet({ id: 'w2', setNumber: 2, isWarmup: true, reps: 0 }),
          mkSet({ id: 's1', setNumber: 3, isWarmup: false }),
        ],
      });
      const state = createInitialState([ex], 0, mkSettings({ autoAddSets: false }));
      let s = apply(state, { type: 'UPDATE_SET', payload: { field: 'weight', value: 20 } });
      s = apply(s, { type: 'COMPLETE_SET' });
      expect(s.exercises[0]!.sets![1]!.weight).toBe(20); // next warmup seeded
      expect(s.exercises[0]!.sets![2]!.weight).toBe(0); // working set untouched
    });
  });
});
