-- ============================================================================
-- PRODUCT EVENTS — the minimum telemetry a paid product needs
-- ============================================================================
-- Analytics were previously written to localStorage only (src/services/eventTracker.ts),
-- which means the operator could never answer the questions that decide whether
-- a subscription business works: how many people finish onboarding, how many
-- complete a first workout, how many see the paywall, how many start checkout,
-- how many convert.
--
-- Rather than adding a third-party SDK (which would widen the privacy surface and
-- the consent burden), events land in our own table:
--   • Clients may INSERT their own rows and nothing else. There is no client
--     SELECT policy, so one user can never read another's behaviour.
--   • The payload is a constrained `props` jsonb; the event name is checked
--     against an allow-list so the table cannot become a dumping ground.
--   • Writes only happen after the user grants analytics consent
--     (src/services/tracking/trackingConsent.ts), which the client enforces.
--
-- Aggregate reporting is expected to run with the service role (SQL editor,
-- scheduled job or a BI connection), not from the browser.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.product_events (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name       text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 64),
  props      jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- Client-side occurrence time; `created_at` is the trusted server time. Both
  -- are kept so clock skew is visible instead of silently distorting funnels.
  occurred_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS product_events_name_created_idx
  ON public.product_events (name, created_at DESC);
CREATE INDEX IF NOT EXISTS product_events_user_idx
  ON public.product_events (user_id, created_at DESC);

ALTER TABLE public.product_events ENABLE ROW LEVEL SECURITY;

-- Insert-own only. Deliberately NO select/update/delete policy for clients.
DROP POLICY IF EXISTS product_events_insert_own ON public.product_events;
CREATE POLICY product_events_insert_own ON public.product_events
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = user_id
    -- Allow-list mirrors FUNNEL_EVENTS in src/services/analytics/funnel.ts.
    AND name IN (
      'signup_completed',
      'onboarding_completed',
      'workout_started',
      'workout_completed',
      'first_workout_completed',
      'paywall_viewed',
      'checkout_started',
      'checkout_completed',
      'subscription_cancelled',
      'coach_invite_accepted',
      'sync_failed',
      'unsynced_changes_held'
    )
    -- Bound the payload so a client cannot store arbitrary blobs.
    AND pg_column_size(props) < 2048
  );

REVOKE SELECT, UPDATE, DELETE ON public.product_events FROM anon, authenticated;

COMMENT ON TABLE public.product_events IS
  'Append-only product funnel events. Clients insert their own rows only; reporting runs with the service role.';
